;;; codex-test.el --- Preset QA adapter checks -*- lexical-binding: t; -*-
(require 'ert)
(unless (ert-test-boundp 'lens-isolated-runtime)
  (load (expand-file-name "tests/review-test.el" lens-root) nil t))

(ert-deftest lens-codex-loaded-readonly-and-key-scope ()
  (should (featurep 'codex))
  (should (featurep 'codex-app-server))
  (should (package-installed-p 'codex '(0 4 0)))
  (should (eq codex-terminal-backend 'app-server))
  (should (eq codex-sandbox-mode 'read-only))
  (should (eq codex-approval-policy 'on-request))
  (should-not codex-full-auto)
  (should-not codex-enable-hooks)
  (with-temp-buffer
    (let ((codex--buffer-directory "/tmp/fixture/"))
      (should (equal (alist-get 'sandbox (codex--app-server-thread-start-params)) "read-only"))
      (should (equal (alist-get 'approvalPolicy (codex--app-server-thread-start-params)) "on-request"))))
  (dolist (mode '(clojure-mode tuareg-mode))
    (with-temp-buffer
      (funcall mode)
      (should (eq (key-binding "c") 'lens-codex-question))
      (should (eq (key-binding "f") 'project-find-file))
      (read-only-mode -1)
      (should (eq (key-binding "c") 'self-insert-command))
      (should (eq (key-binding "f") 'self-insert-command))
      (read-only-mode 1)
      (lens-reading-mode -1)
      (should (eq (key-binding "c") 'self-insert-command))
      (should (eq (key-binding "f") 'self-insert-command))))
  (with-temp-buffer
    (emacs-lisp-mode)
    (should (eq (key-binding "c") 'self-insert-command))))

(ert-deftest lens-codex-presets-capture-source-before-selection ()
  (lens-test-project
   (let ((file (expand-file-name "空间 文件.mli" directory)) captured)
     (with-temp-file file (insert "val answer : int -> int\n"))
     (switch-to-buffer (find-file-noselect file))
     (goto-char 5)
     (let ((source (current-buffer)) (origin (point)) (text (buffer-string)))
       (cl-letf (((symbol-function 'completing-read)
                  (lambda (_prompt candidates &rest _)
                    (switch-to-buffer (get-buffer-create " *fake codex target*"))
                    (car (last candidates))))
                 ((symbol-function 'lens-codex-dispatch)
                  (lambda (context prompt) (setq captured (list context prompt)))))
         (lens-codex-question))
       (should (equal (plist-get (car captured) :file) file))
       (should (equal (plist-get (car captured) :root) (file-name-as-directory directory)))
       (should (string-match-p (regexp-quote "给我解释当前文件<空间 文件.mli>中最重要的几个类型和函数") (cadr captured)))
       (should (string-match-p (regexp-quote file) (cadr captured)))
       (should (string-match-p "val answer" (cadr captured)))
       (with-current-buffer source
         (should (= origin (point)))
         (should (equal text (buffer-string)))
         (should buffer-read-only))))))

(ert-deftest lens-codex-cancel-and-fileless-do-not-dispatch ()
  (lens-test-project
   (with-current-buffer (find-file-noselect clj)
     (let ((calls 0))
       (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) (signal 'quit nil)))
                 ((symbol-function 'lens-codex-dispatch) (lambda (&rest _) (cl-incf calls))))
         (condition-case nil (lens-codex-question) (quit nil)))
       (should (= calls 0))))
   (with-temp-buffer
     (clojure-mode)
     (should-error (lens-codex-question) :type 'user-error))))

(ert-deftest lens-codex-cli-and-login-errors-are-friendly ()
  (lens-test-project
   (with-current-buffer (find-file-noselect clj)
     (let ((context (lens-codex-source-context)))
       (let ((lens-codex-program "nonexistent-code-lens-cli"))
         (should-error (lens-codex-dispatch context "fixture") :type 'user-error))
       (cl-letf (((symbol-function 'call-process) (lambda (&rest _) 1)))
         (should-error (lens-codex-dispatch context "fixture") :type 'user-error)))))
  (with-temp-buffer
    (setq-local lens-codex-session-p t)
    (let ((codex--app-server-effective-permissions '((sandboxPolicy (type . "workspaceWrite")))))
      (should-error (lens-codex-check-turn-permissions nil) :type 'user-error))))

(ert-deftest lens-codex-interactive-preset-and-cancel ()
  :tags '(interactive)
  (skip-unless (not noninteractive))
  (lens-test-project
   (dolist (file (list clj ml))
     (switch-to-buffer (find-file-noselect file))
     (let (sent)
       (cl-letf (((symbol-function 'lens-codex-dispatch)
                  (lambda (context prompt) (setq sent (list context prompt)))))
         (execute-kbd-macro (vconcat "c" "glossary" (kbd "RET")))
         (should sent)
         (should (string-match-p (regexp-quote (file-name-nondirectory file)) (cadr sent)))
         (setq sent nil)
         (execute-kbd-macro (vconcat "c" "函数" (kbd "RET")))
         (should sent)
         (should (string-match-p "中最重要的几个类型和函数" (cadr sent)))
         (should (equal (plist-get (car sent) :file) file))
         (setq sent nil)
         (execute-kbd-macro (vconcat "c" (kbd "C-g")))
         (setq quit-flag nil)
         (should-not sent))
       (should buffer-read-only)
       (read-only-mode -1)
       (goto-char (point-max))
       (execute-kbd-macro "c")
       (should (= (char-before) ?c))))))

(ert-deftest lens-codex-real-synthetic-question ()
  :tags '(external)
  (skip-unless (equal (getenv "CODE_LENS_REAL_QA") "1"))
  (lens-test-project
   (let ((file (if (string-prefix-p "29" emacs-version) clj ml))
         session completed answers)
     (let ((capture (lambda (params)
                      (let ((item (alist-get 'item params)))
                        (when (equal (alist-get 'type item) "agentMessage")
                          (push (alist-get 'text item) answers)))))
           (finish (lambda (params)
                     (setq completed t)
                     (let ((turn (alist-get 'turn params)))
                       (message "CLI turn status=%s error=%s"
                                (alist-get 'status turn)
                                (alist-get 'message (alist-get 'error turn)))))))
       (advice-add 'codex--app-server-render-completed-item :before capture)
       (advice-add 'codex--app-server-turn-completed :after finish)
       (unwind-protect
           (progn
             (switch-to-buffer (find-file-noselect file))
             (let ((source (current-buffer)) (text (buffer-string)))
               ;; Only preset selection is stubbed. Real package, CLI, protocol and model are used.
               (cl-letf (((symbol-function 'completing-read)
                          (lambda (_prompt candidates &rest _) (car candidates))))
                 (setq session (lens-codex-question)))
               (let ((deadline (+ (float-time) 120)))
                 (while (and (not completed) (< (float-time) deadline))
                   (accept-process-output nil 0.1)))
               (should completed)
               (should (cl-some (lambda (answer) (and (stringp answer) (string-match-p "answer" answer))) answers))
               (with-current-buffer session
                 (lens-codex-check-turn-permissions)
                 (message "REAL QA Emacs=%s readonly=%s approval=%s answer=%S"
                          emacs-version
                          (alist-get 'type (alist-get 'sandboxPolicy codex--app-server-effective-permissions))
                          (alist-get 'approvalPolicy codex--app-server-effective-permissions)
                          answers))
               (with-current-buffer source
                 (should buffer-read-only)
                 (should (equal text (buffer-string))))
               (should (equal "" (with-temp-buffer (call-process "git" nil t nil "diff" "--") (buffer-string))))))
         (advice-remove 'codex--app-server-render-completed-item capture)
         (advice-remove 'codex--app-server-turn-completed finish)
         (when (buffer-live-p session)
           (with-current-buffer session
             (let ((codex-confirm-kill nil)) (codex--term-kill-process 'app-server session)))
           (when (buffer-live-p session) (kill-buffer session))))))))

(ert-deftest lens-codex-interactive-project-file-key ()
  :tags '(interactive)
  (skip-unless (not noninteractive))
  (lens-test-project
   (dolist (pair (list (cons clj ml) (cons ml clj)))
     (switch-to-buffer (find-file-noselect (car pair)))
     (execute-kbd-macro (vconcat "f" (file-name-nondirectory (cdr pair)) (kbd "RET")))
     (should (equal buffer-file-name (cdr pair)))
     (should buffer-read-only)
     (read-only-mode -1)
     (goto-char (point-max))
     (execute-kbd-macro "f")
     (should (= (char-before) ?f))
     (read-only-mode 1))))

(ert-deftest lens-codex-advertised-model-is-session-local ()
  (let ((codex-model "unchanged-global") proceeded)
    (with-temp-buffer
      (setq-local lens-codex-session-p t)
      (cl-letf (((symbol-function 'codex--app-server-send-request)
                 (lambda (method _params callback)
                   (should (equal method "model/list"))
                   (funcall callback '((data . [((model . "first") (isDefault . :false))
                                                ((model . "advertised") (isDefault . t)
                                                 (defaultReasoningEffort . "medium"))])) nil))))
        (lens-codex-initialize-model (lambda () (setq proceeded codex-model))))
      (should (equal proceeded "advertised"))
      (should (equal codex-reasoning-effort "medium")))
    (should (equal codex-model "unchanged-global"))))

(ert-deftest lens-codex-first-question-waits-for-confirmed-permissions ()
  (with-temp-buffer
    (setq-local lens-codex-session-p t)
    (setq-local lens-codex-pending-question "synthetic question")
    (let (sent)
      (cl-letf (((symbol-function 'codex--send-command-to-buffer)
                 (lambda (prompt _buffer) (push prompt sent))))
        (lens-codex-send-initial-question)
        (should-not sent)
        (should lens-codex-pending-question)
        (setq-local codex--app-server-effective-permissions
                    '((approvalPolicy . "on-request") (sandboxPolicy (type . "readOnly"))))
        (lens-codex-send-initial-question)
        (lens-codex-send-initial-question)
        (should (equal sent '("synthetic question")))
        (should-not lens-codex-pending-question)))))
