;;; codex-test.el --- Preset QA adapter checks -*- lexical-binding: t; -*-
(require 'ert)
(unless (ert-test-boundp 'lens-isolated-runtime)
  (load (expand-file-name "tests/review-test.el" lens-root) nil t))

(ert-deftest lens-codex-loaded-readonly-and-key-scope ()
  (should (featurep 'codex-ide))
  (should-not (featurep 'codex))
  (should (package-installed-p 'codex-ide '(0 3 2)))
  (should (equal codex-ide-sandbox-mode "read-only"))
  (should (equal codex-ide-approval-policy "on-request"))
  (should-not codex-ide-emacs-context-policy)
  (should-not codex-ide-want-mcp-bridge)
  (lens-test-project
   (should (equal (alist-get 'cwd (codex-ide--thread-start-params)) directory))
   (should (equal (alist-get 'sandbox (codex-ide--thread-start-params)) "read-only"))
   (should (equal (alist-get 'approvalPolicy (codex-ide--thread-start-params)) "on-request")))
  (dolist (mode '(clojure-mode tuareg-mode))
    (with-temp-buffer
      (funcall mode)
      (should (eq (key-binding "c") 'lens-codex-question))
      (should (eq (key-binding "f") 'project-find-file))
      (read-only-mode -1)
      (should (eq (key-binding "c") 'self-insert-command))
      (should (eq (key-binding "f") 'self-insert-command))
      (read-only-mode 1)
      (lens-reading-mode -1)
      (should (eq (key-binding "c") 'self-insert-command))
      (should (eq (key-binding "f") 'self-insert-command))))
  (with-temp-buffer
    (emacs-lisp-mode)
    (should (eq (key-binding "c") 'self-insert-command))))

(ert-deftest lens-codex-presets-capture-source-before-selection ()
  (lens-test-project
   (dolist (relative '("src/空间 文件.mli" "test/空间 文件.mli"))
     (let ((file (expand-file-name relative directory)) captured)
       (make-directory (file-name-directory file) t)
       (with-temp-file file (insert "val unique_saved_answer : int -> int\n"))
       (switch-to-buffer (find-file-noselect file))
       (let ((inhibit-read-only t)) (goto-char (point-max)) (insert "UNSAVED_PRIVATE_SELECTION"))
       (goto-char 5)
       (push-mark (point-max) t t)
       (let ((source (current-buffer)) (origin (point)) (text (buffer-string)))
         (cl-letf (((symbol-function 'completing-read)
                    (lambda (miniprompt candidates &rest _)
                      (should (string-match-p "未保存修改" miniprompt))
                      (should (equal candidates (mapcar (lambda (template) (format template relative)) lens-codex-prompt-templates)))
                      (switch-to-buffer (get-buffer-create " *fake codex target*"))
                      (car (last candidates))))
                   ((symbol-function 'lens-codex-dispatch)
                    (lambda (context prompt) (setq captured (list context prompt)))))
           (lens-codex-question))
         (should (eq (plist-get (car captured) :buffer) source))
         (should (plist-get (car captured) :project))
         (should (equal (plist-get (car captured) :relative-file) relative))
         (should (equal (plist-get (car captured) :file) file))
         (should (equal (plist-get (car captured) :root) (file-name-as-directory directory)))
         (should (string-match-p (regexp-quote (format "给我解释当前文件<%s>中最重要的几个类型和函数" relative)) (cadr captured)))
         (should-not (plist-member (car captured) :text))
         (should-not (plist-member (car captured) :region))
         (should-not (string-match-p (regexp-quote directory) (cadr captured)))
         (dolist (token '("unique_saved_answer" "UNSAVED_PRIVATE_SELECTION"))
           (should-not (string-match-p (regexp-quote token) (cadr captured))))
         (should (equal (with-temp-buffer (insert-file-contents file) (buffer-string)) "val unique_saved_answer : int -> int\n"))
         (with-current-buffer source
           (should (= origin (point)))
           (should (equal text (buffer-string)))
           (should (buffer-modified-p))
           (should buffer-read-only)))))))

(ert-deftest lens-codex-cancel-and-fileless-do-not-dispatch ()
  (lens-test-project
   (with-current-buffer (find-file-noselect clj)
     (let ((calls 0))
       (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) (signal 'quit nil)))
                 ((symbol-function 'lens-codex-dispatch) (lambda (&rest _) (cl-incf calls))))
         (condition-case nil (lens-codex-question) (quit nil)))
       (should (= calls 0))))
   (with-temp-buffer
     (clojure-mode)
     (should-error (lens-codex-question) :type 'user-error))))

(ert-deftest lens-codex-cli-and-login-errors-are-friendly ()
  (lens-test-project
   (with-current-buffer (find-file-noselect clj)
     (let ((context (lens-codex-source-context)))
       (let ((lens-codex-program "nonexistent-code-lens-cli"))
         (should-error (lens-codex-dispatch context "fixture") :type 'user-error))
       (cl-letf (((symbol-function 'call-process) (lambda (&rest _) 1)))
         (should-error (lens-codex-dispatch context "fixture") :type 'user-error)))))
  (should-error (lens-codex-check-session nil "/tmp/") :type 'user-error))

(ert-deftest lens-codex-interactive-preset-and-cancel ()
  :tags '(interactive)
  (skip-unless (not noninteractive))
  (lens-test-project
   (dolist (file (list clj ml))
     (switch-to-buffer (find-file-noselect file))
     (let (sent)
       (cl-letf (((symbol-function 'lens-codex-dispatch)
                  (lambda (context prompt) (setq sent (list context prompt)))))
         (execute-kbd-macro (vconcat "c" "glossary" (kbd "RET")))
         (should sent)
         (should (string-match-p (regexp-quote (file-name-nondirectory file)) (cadr sent)))
         (setq sent nil)
         (execute-kbd-macro (vconcat "c" "函数" (kbd "RET")))
         (should sent)
         (should (string-match-p "中最重要的几个类型和函数" (cadr sent)))
         (should (equal (plist-get (car sent) :file) file))
         (setq sent nil)
         (execute-kbd-macro (vconcat "c" (kbd "C-g")))
         (setq quit-flag nil)
         (should-not sent))
       (should buffer-read-only)
       (read-only-mode -1)
       (goto-char (point-max))
       (execute-kbd-macro "c")
       (should (= (char-before) ?c))))))

(ert-deftest lens-codex-real-synthetic-question ()
  :tags '(external)
  (skip-unless (equal (getenv "CODE_LENS_REAL_QA") "1"))
  (lens-test-project
   (let* ((relative (if (string-prefix-p "29" emacs-version) "src/clj/review.clj" "src/ml/review.ml"))
          (file (expand-file-name relative directory)) session completed answers wire)
     (let ((capture (lambda (_session message)
                      (let* ((method (alist-get 'method message)) (params (alist-get 'params message))
                             (item (alist-get 'item params)))
                        (when (and (equal method "item/completed") (equal (alist-get 'type item) "agentMessage"))
                          (push (alist-get 'text item) answers))
                        (when (equal method "turn/completed")
                          (setq completed t)
                          (message "CLI turn status=%s" (alist-get 'status (alist-get 'turn params)))))))
           (sent (lambda (_session payload)
                   (when (equal (alist-get 'method payload) "turn/start")
                     (setq wire (alist-get 'params payload))))))
       (advice-add 'codex-ide--handle-notification :before capture)
       (advice-add 'codex-ide--jsonrpc-send :before sent)
       (unwind-protect
           (progn
             (make-directory (file-name-directory file) t)
             (with-temp-file file
               (insert-file-contents (if (string-prefix-p "29" emacs-version) clj ml))
               (goto-char (point-min))
               (while (search-forward "answer" nil t) (replace-match "answer_from_saved_fixture" t t)))
             (switch-to-buffer (find-file-noselect file))
             (let ((source (current-buffer)) (text (buffer-string)))
               (if noninteractive
                   (cl-letf (((symbol-function 'completing-read) (lambda (_prompt candidates &rest _) (car candidates))))
                     (lens-codex-question))
                 ;; The complete real selection -> new public package API -> CLI chain.
                 (execute-kbd-macro (vconcat "c" "glossary" (kbd "RET"))))
               (setq session (gethash (file-name-as-directory directory) lens-codex-sessions))
               (should session)
               (let ((deadline (+ (float-time) 120)))
                 (while (and (not completed) (< (float-time) deadline)) (accept-process-output nil 0.1)))
               (should completed)
               (should (cl-some (lambda (answer) (and (stringp answer) (string-match-p "answer_from_saved_fixture" answer))) answers))
               (should wire)
               (let ((question (alist-get 'text (elt (alist-get 'input wire) 0))))
                 (should (string-match-p (regexp-quote (concat "<" relative ">")) question))
                 (should-not (string-match-p "answer_from_saved_fixture" question))
                 (should-not (string-match-p (regexp-quote directory) question))
                 (should-not (string-match-p "Emacs prompt context" question)))
               (should (equal (alist-get 'approvalPolicy wire) "on-request"))
               (should (equal (alist-get 'type (alist-get 'sandboxPolicy wire)) "readOnly"))
               (lens-codex-check-session session (file-name-as-directory directory))
               (should (equal (codex-ide-session-directory session) directory))
               (message "REAL Codex IDE Emacs=%s relative=%s root-confirmed=t readOnly/on-request=t answer=%S" emacs-version relative answers)
               (with-current-buffer source (should buffer-read-only) (should (equal text (buffer-string))))
               (should (equal "" (with-temp-buffer (call-process "git" nil t nil "diff" "--") (buffer-string))))))
         (advice-remove 'codex-ide--handle-notification capture)
         (advice-remove 'codex-ide--jsonrpc-send sent)
         (when session
           (when (buffer-live-p (codex-ide-session-buffer session)) (kill-buffer (codex-ide-session-buffer session)))
           (remhash (file-name-as-directory directory) lens-codex-sessions)
           (remhash session lens-codex-permissions)))))))

(ert-deftest lens-codex-interactive-project-file-key ()
  :tags '(interactive)
  (skip-unless (not noninteractive))
  (lens-test-project
   (dolist (pair (list (cons clj ml) (cons ml clj)))
     (switch-to-buffer (find-file-noselect (car pair)))
     (execute-kbd-macro (vconcat "f" (file-name-nondirectory (cdr pair)) (kbd "RET")))
     (should (equal buffer-file-name (cdr pair)))
     (should buffer-read-only)
     (read-only-mode -1)
     (goto-char (point-max))
     (execute-kbd-macro "f")
     (should (= (char-before) ?f))
     (read-only-mode 1))))

(ert-deftest lens-codex-requested-defaults-and-session-overrides ()
  (lens-test-project
   (with-temp-buffer
     (setq default-directory (file-name-as-directory directory))
     (let* ((session (make-codex-ide-session :directory directory :buffer (current-buffer)))
            (params (codex-ide--thread-start-params session)))
       (should (equal (alist-get 'model params) "gpt-6.1-sol"))
       (should (equal (alist-get 'model_reasoning_effort (alist-get 'config params)) "high"))
       (codex-ide-config-set-session-value 'model "explicit-session-model" session)
       (codex-ide-config-set-session-value 'reasoning-effort "low" session)
       (lens-codex-session-event 'status-changed session '(:reason initialized))
       (let ((overridden (codex-ide--thread-start-params session)))
         (should (equal (alist-get 'model overridden) "explicit-session-model"))
         (should (equal (alist-get 'model_reasoning_effort (alist-get 'config overridden)) "low")))))))

(ert-deftest lens-codex-first-question-waits-for-confirmed-permissions ()
  (let ((lens-codex-sessions (make-hash-table :test 'equal))
        (lens-codex-permissions (make-hash-table :test 'eq)))
    (with-temp-buffer
      (let ((session (make-codex-ide-session :directory (file-truename "/tmp") :buffer (current-buffer))))
        (puthash (file-name-as-directory (file-truename "/tmp")) session lens-codex-sessions)
        (should-error (lens-codex-check-session session "/tmp/") :type 'user-error)
        (should-error (lens-codex-confirm-thread (lambda (&rest _) nil) session "thread/start" nil) :type 'user-error)
        (lens-codex-confirm-thread
         (lambda (&rest _) `((thread (cwd . ,(file-truename "/tmp")))
                            (approvalPolicy . "on-request") (sandbox (type . "readOnly"))))
         session "thread/start" nil)
        (should (gethash session lens-codex-permissions))))))

(ert-deftest lens-codex-path-context-rejects-unsupported-files ()
  (lens-test-project
   (with-current-buffer (find-file-noselect clj)
     (cl-letf (((symbol-function 'project-current) (lambda (&rest _) nil)))
       (should-error (lens-codex-source-context) :type 'user-error))
     (let ((other (expand-file-name "other/" directory)))
       (make-directory other)
       (cl-letf (((symbol-function 'project-root) (lambda (_) other)))
         (should-error (lens-codex-source-context) :type 'user-error))))
   (with-temp-buffer
     (tuareg-mode)
     (setq buffer-file-name (expand-file-name "not-yet-saved.ml" directory))
     (should-error (lens-codex-question) :type 'user-error)
     (setq buffer-file-name "/ssh:example.invalid:/code.ml")
     (should-error (lens-codex-question) :type 'user-error))
   (let ((outside (make-temp-file "lens-outside-" nil ".ml"))
         (link (expand-file-name "outside.ml" directory)))
     (unwind-protect
         (progn
           (make-symbolic-link outside link)
           (with-temp-buffer
             (tuareg-mode)
             (setq buffer-file-name link)
             (should-error (lens-codex-source-context) :type 'user-error)))
       (delete-file outside)))))

(ert-deftest lens-codex-dispatch-keeps-project-cwd-and-reuse-separate ()
  (lens-test-project
   (let* ((root (file-name-as-directory directory)) (other (expand-file-name "other-project/" directory))
          (lens-codex-sessions (make-hash-table :test 'equal))
          (lens-codex-permissions (make-hash-table :test 'eq))
          (a (generate-new-buffer " *QA project A*")) (b (generate-new-buffer " *QA project B*"))
          (session (make-codex-ide-session :directory directory :buffer a)) sent started)
     (make-directory other)
     (call-process "git" nil nil nil "init" "-q" other)
     (puthash root session lens-codex-sessions) (puthash session t lens-codex-permissions)
     (unwind-protect
         (cl-letf (((symbol-function 'executable-find) (lambda (_) "/fixture/codex"))
                   ((symbol-function 'call-process) (lambda (&rest _) 0))
                   ((symbol-function 'process-live-p) (lambda (_) t))
                   ((symbol-function 'codex-ide-transcript-submit-prompt-to-session)
                    (lambda (target prompt &rest options)
                      (should (plist-get options :suppress-context))
                      (push (list (codex-ide-session-directory target) prompt) sent)))
                   ((symbol-function 'pop-to-buffer) (lambda (buffer &rest _) buffer))
                   ((symbol-function 'codex-ide)
                    (lambda ()
                      (setq started default-directory)
                      (let ((new (make-codex-ide-session :directory (directory-file-name other) :buffer b)))
                        (puthash other new lens-codex-sessions) (puthash new t lens-codex-permissions)
                        (should (equal (alist-get 'cwd (codex-ide--thread-start-params new)) (directory-file-name other)))
                        new))))
           (lens-codex-dispatch (list :root root) "src/a/review.ml")
           (lens-codex-dispatch (list :root other) "src/b/review.ml")
           (should (equal started other))
           (should (equal (nreverse sent) (list (list directory "src/a/review.ml") (list (directory-file-name other) "src/b/review.ml"))))
           (setf (codex-ide-session-directory session) (directory-file-name other))
           (should-error (lens-codex-dispatch (list :root root) "wrong project") :type 'user-error))
       (kill-buffer a) (kill-buffer b)))))

(ert-deftest lens-codex-real-same-name-project-session-switch ()
  :tags '(external)
  (skip-unless (equal (getenv "CODE_LENS_REAL_QA") "1"))
  (lens-test-project
   (let ((lens-codex-sessions (make-hash-table :test 'equal))
         (lens-codex-permissions (make-hash-table :test 'eq)) sessions sent)
     (unwind-protect
         (progn
           (dolist (prefix '("a/repo" "b/repo"))
             (let* ((root (expand-file-name prefix directory)) (file (expand-file-name "src/空间 文件.ml" root)))
               (make-directory (file-name-directory file) t)
               (call-process "git" nil nil nil "init" "-q" root)
               (with-temp-file file (insert "let saved_fixture = 42\n"))))
           ;; Real new-package processes and thread/start; only the model submission is suppressed.
           (cl-letf (((symbol-function 'codex-ide-transcript-submit-prompt-to-session)
                      (lambda (session _prompt &rest options)
                        (should (plist-get options :suppress-context)) (push session sent))))
             (dolist (prefix '("a/repo" "b/repo" "a/repo"))
               (let* ((root (file-name-as-directory (expand-file-name prefix directory)))
                      (file (expand-file-name "src/空间 文件.ml" root)))
                 (switch-to-buffer (find-file-noselect file))
                 (let ((context (lens-codex-source-context)))
                   (should (equal (plist-get context :relative-file) "src/空间 文件.ml"))
                   (lens-codex-dispatch context "metadata-only; model submission suppressed")
                   (let ((session (gethash root lens-codex-sessions)))
                     (cl-pushnew session sessions)
                     (lens-codex-check-session session root)
                     (should (eq (current-buffer) (codex-ide-session-buffer session)))
                     (should (equal (buffer-local-value 'default-directory (current-buffer)) root)))))))
           (should (= (length sessions) 2))
           (should (eq (car sent) (car (last sent))))
           (should-not (eq (car sent) (cadr sent)))
           (should-not (eq (codex-ide-session-buffer (car sessions)) (codex-ide-session-buffer (cadr sessions))))
           (should-not (eq (codex-ide-session-process (car sessions)) (codex-ide-session-process (cadr sessions))))
           (should-not (equal (codex-ide-session-thread-id (car sessions)) (codex-ide-session-thread-id (cadr sessions))))
           (message "REAL project switching Emacs=%s same basename repo, two distinct buffers/processes/threads, A->B->A reused exactly; no model question sent" emacs-version))
       (maphash (lambda (_root session)
                  (when (buffer-live-p (codex-ide-session-buffer session)) (kill-buffer (codex-ide-session-buffer session)))) lens-codex-sessions)))))

(ert-deftest lens-codex-free-question-keeps-captured-file-context ()
  (lens-test-project
   (let* ((relative "src/空间 文件.mli") (file (expand-file-name relative directory)) sent)
     (make-directory (file-name-directory file) t)
     (with-temp-file file (insert "val saved_private_fixture : int\n"))
     (switch-to-buffer (find-file-noselect file))
     (let ((inhibit-read-only t)) (insert "UNSAVED_PRIVATE_FIXTURE"))
     (let ((source (current-buffer)) (text (buffer-string))
           (question "自定义：为什么保留 100% 的值？"))
       (cl-letf (((symbol-function 'completing-read)
                  (lambda (_prompt _choices _predicate require-match &rest _)
                    (should-not require-match)
                    (switch-to-buffer (get-buffer-create " *free-question-other-target*"))
                    question))
                 ((symbol-function 'lens-codex-dispatch)
                  (lambda (context prompt) (setq sent (list context prompt)))))
         (lens-codex-question))
       (should (eq (plist-get (car sent) :buffer) source))
       (should (equal (plist-get (car sent) :root) (file-name-as-directory directory)))
       (should (equal (plist-get (car sent) :relative-file) relative))
       (should (string-match-p (regexp-quote (concat "当前文件<" relative ">\n" question)) (cadr sent)))
       (should-not (string-match-p (regexp-quote directory) (cadr sent)))
       (should-not (string-match-p "saved_private_fixture\\|UNSAVED_PRIVATE_FIXTURE" (cadr sent)))
       (with-current-buffer source
         (should (equal text (buffer-string)))
         (should (buffer-modified-p))
         (should buffer-read-only))))))

(ert-deftest lens-codex-empty-questions-do-not-dispatch ()
  (lens-test-project
   (with-current-buffer (find-file-noselect clj)
     (let ((calls 0))
       (dolist (blank '("" " " "\t\n\r "))
         (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) blank))
                   ((symbol-function 'lens-codex-dispatch) (lambda (&rest _) (cl-incf calls))))
           (should-error (lens-codex-question) :type 'user-error)))
       (should (= calls 0))))))

(ert-deftest lens-codex-interactive-free-question-and-empty-input ()
  :tags '(interactive)
  (skip-unless (not noninteractive))
  (should vertico-mode)
  (should (memq 'orderless completion-styles))
  (lens-test-project
   (dolist (file (list clj ml))
     (switch-to-buffer (find-file-noselect file))
     (let ((source (current-buffer)) (text (buffer-string)) sent
           (question "WHY_UNMATCHED_100%_QUESTION")
           (outside-map vertico-map))
       (cl-letf (((symbol-function 'lens-codex-dispatch)
                  (lambda (context prompt) (setq sent (list context prompt)))))
         ;; Real c -> Vertico/Orderless -> unmatched input -> RET -> dispatcher.
         (execute-kbd-macro (vconcat "c" question (kbd "RET")))
         (should (eq (plist-get (car sent) :buffer) source))
         (should (string-match-p (regexp-quote question) (cadr sent)))
         (should (string-match-p (regexp-quote (concat "当前文件<" (file-relative-name file directory) ">")) (cadr sent)))
         (should (eq outside-map vertico-map))
         ;; A literal input that partially matches a preset remains available via M-RET.
         (setq sent nil)
         (execute-kbd-macro (vconcat "c" "glossary" (kbd "M-RET")))
         (should (string-suffix-p "\nglossary" (cadr sent)))
         ;; Explicit candidate selection with no typed text still works.
         (setq sent nil)
         (execute-kbd-macro (vconcat "c" (kbd "C-n RET")))
         (should sent)
         (should (cl-some (lambda (template)
                            (string-suffix-p (format template (file-relative-name file directory)) (cadr sent)))
                          lens-codex-prompt-templates))
         (dolist (blank '("" "   "))
           (setq sent nil)
           (should-error (execute-kbd-macro (vconcat "c" blank (kbd "RET"))) :type 'user-error)
           (should-not sent))
         (setq sent nil)
         (execute-kbd-macro (vconcat "c" question (kbd "C-g")))
         (setq quit-flag nil)
         (should-not sent))
       (should (eq source (current-buffer)))
       (should (equal text (buffer-string)))
       (should buffer-read-only)))
   (message "REAL free-question Emacs=%s: unmatched RET, literal M-RET, explicit preset; empty/whitespace/cancel no dispatch"
            emacs-version)))
