;;; input-source-test.el --- Foreground system input source policy -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(unless (ert-test-boundp 'lens-isolated-runtime)
  (load (expand-file-name "tests/review-test.el" lens-root) nil t))

(ert-deftest lens-input-source-classification-and-no-internal-ime ()
  (should (fboundp 'lens-input-source-role))
  (let ((lens-eglot-auto-start nil))
    (with-temp-buffer (tuareg-mode) (should (eq (lens-input-source-role) 'english)))
    (with-temp-buffer (clojure-mode) (should (eq (lens-input-source-role) 'english)))
    (with-temp-buffer
      (codex-ide-session-mode)
      (should (eq (lens-input-source-role) 'chinese)))
    (with-temp-buffer
      (text-mode) (rename-buffer "*codex[pretend]*" t)
      (should-not (lens-input-source-role)))
    (with-temp-buffer
      (require 'term) (term-mode)
      (rename-buffer "*codex terminal*" t)
      (should-not (lens-input-source-role)))
    (with-temp-buffer (minibuffer-inactive-mode) (should-not (lens-input-source-role))))
  (should-not (string-match-p "activate-input-method\\|set-input-method"
                             (with-temp-buffer
                               (insert-file-contents (expand-file-name "lisp/lens-input-source.el" lens-root))
                               (buffer-string)))))

(defconst lens-input-source-test-state
  '(:current "com.apple.keylayout.ABC" :frontmost_pid 123
    :sources [(:id "com.apple.keylayout.ABC" :languages ["en"])
              (:id "com.apple.inputmethod.SCIM.ITABC" :languages ["zh-Hans"])]))

(ert-deftest lens-input-source-targets-and-chinese-preference ()
  (let ((lens-input-source-english nil) (lens-input-source-chinese nil)
        (lens-input-source--recent-chinese nil))
    (should (equal (lens-input-source-target 'english lens-input-source-test-state)
                   "com.apple.keylayout.ABC"))
    (should (equal (lens-input-source-target 'chinese lens-input-source-test-state)
                   "com.apple.inputmethod.SCIM.ITABC"))
    (let* ((other "org.example.chinese")
           (state (copy-tree lens-input-source-test-state)))
      (setf (plist-get state :sources)
            (vconcat (plist-get state :sources) (vector (list :id other :languages ["zh"])) ))
      (should-error (lens-input-source-target 'chinese state) :type 'user-error)
      (setf (plist-get state :current) other)
      (should (equal (lens-input-source-target 'chinese state) other))
      (setf (plist-get state :current) "com.apple.keylayout.ABC")
      (should (equal (lens-input-source-target 'chinese state) other))
      (let ((lens-input-source-chinese "com.apple.inputmethod.SCIM.ITABC"))
        (should (equal (lens-input-source-target 'chinese state)
                       "com.apple.inputmethod.SCIM.ITABC")))))
  (let ((lens-input-source-english "missing"))
    (should-error (lens-input-source-target 'english lens-input-source-test-state) :type 'user-error)))

(defmacro lens-input-source-test-policy (&rest body)
  "Exercise actual policy with controlled async transport and no system mutation."
  `(let ((lens-input-source-mode t) (lens-input-source--seen :initial)
         (lens-input-source--desired nil) (lens-input-source--job nil)
         (lens-input-source--process nil) (lens-input-source--timer nil)
         (lens-input-source--failed nil) (lens-input-source--recent-chinese nil)
         (lens-input-source-english nil) (lens-input-source-chinese nil)
         events callbacks focused)
     (cl-letf (((symbol-function 'emacs-pid) (lambda () 123))
               ((symbol-function 'lens-input-source-context) (lambda () focused))
               ((symbol-function 'lens-input-source-start-request)
                (lambda (arguments callback)
                  (push arguments events) (push callback callbacks)
                  (setq lens-input-source--process 'controlled)))
               ((symbol-function 'lens-input-source-schedule)
                (lambda () (unless lens-input-source--process (lens-input-source-pump)))))
       ,@body)))

(defmacro lens-input-source-test-reply (_callbacks &optional state code)
  "Deliver a controlled response in the caller's lexical test fixture."
  `(let ((callback (pop callbacks)))
     (setq lens-input-source--process nil)
     (funcall callback (or ,code 0) (or ,state lens-input-source-test-state))))

(ert-deftest lens-input-source-dedup-and-stale-background ()
  (lens-input-source-test-policy
   (setq focused (list 'frame 'window 'source 'english))
   (lens-input-source-observe)
   (should (= (length events) 1))
   (dotimes (_ 50) (lens-input-source-observe))
   (should (= (length events) 1))
   ;; Current Lisp buffer is irrelevant; only the actual selected window counts.
   (with-temp-buffer (codex-ide-session-mode) (lens-input-source-observe))
   (should (= (length events) 1))
   (lens-input-source-test-reply 'callbacks)
   (should (= (length events) 1)) ; ABC already selected, no setter.
   (setq focused (list 'frame 'chat-window 'chat 'chinese))
   (lens-input-source-observe)
   (should (= (length events) 2))
   ;; A response for a chat that has already been left must never launch a setter.
   (setq focused (list 'frame 'window 'source 'english))
   (lens-input-source-observe)
   (lens-input-source-test-reply 'callbacks)
   (should (equal (car events) '("--inspect")))
   (should (= (length events) 3))
   (lens-input-source-test-reply 'callbacks)
   (should-not lens-input-source--job)
   (should-not lens-input-source--failed)))

(ert-deftest lens-input-source-serialized-setters-and-focus-guard ()
  (lens-input-source-test-policy
   (setq focused (list 'frame 'chat-window 'chat 'chinese))
   (lens-input-source-observe)
   (lens-input-source-test-reply 'callbacks)
   (should (equal (car (car events)) "--select"))
   (setq focused (list 'frame 'window 'source 'english))
   (lens-input-source-observe)
   (should (= (length events) 2)) ; Do not run the next setter concurrently.
   (lens-input-source-test-reply 'callbacks)
   (should (= (length events) 3)) ; Newest context inspects after old setter exits.
   (let ((state (copy-tree lens-input-source-test-state)))
     (setf (plist-get state :current) "com.apple.inputmethod.SCIM.ITABC")
     (lens-input-source-test-reply 'callbacks state))
   (should (equal (cadr (car events)) "com.apple.keylayout.ABC"))
   ;; Losing focus stops follow-up work and cannot mark the stale job successful.
   (setq focused nil)
   (lens-input-source-observe)
   (lens-input-source-test-reply 'callbacks)
   (should-not lens-input-source--job)
   (should-not lens-input-source--failed)))

(ert-deftest lens-input-source-failure-and-hooks ()
  (lens-input-source-test-policy
   (setq focused (list 'frame 'window 'source 'english))
   (lens-input-source-observe)
   (lens-input-source-test-reply 'callbacks nil 2)
   (should lens-input-source--failed)
   (dotimes (_ 20) (lens-input-source-observe))
   (should (= (length events) 1)))
  (should (memq #'lens-input-source-observe window-buffer-change-functions))
  (should (memq #'lens-input-source-observe window-selection-change-functions))
  (should (memq #'lens-input-source-observe post-command-hook))
  (should (string-match-p "系统输入源" (lens-help-text))))

(ert-deftest lens-input-source-real-async-inspection-and-background-rejection ()
  ;; Read the real system only. No request in this test can switch a source.
  (let ((lens-input-source--process nil) result)
    (lens-input-source-start-request
     '("--inspect") (lambda (code state) (setq result (list code state))))
    (let ((deadline (+ (float-time) 3)))
      (while (and (not result) (< (float-time) deadline)) (accept-process-output nil 0.02)))
    (should result)
    (should (= (car result) 0))
    (should (stringp (plist-get (cadr result) :current)))
    (should (vectorp (plist-get (cadr result) :sources)))
    (should-not (cl-find-if (lambda (source)
                             (member (plist-get source :id)
                                     '("com.apple.CharacterPaletteIM" "com.apple.PressAndHold")))
                           (append (plist-get (cadr result) :sources) nil))))
  (lens-input-source-test-policy
   (setq focused (list 'frame 'chat-window 'chat 'chinese))
   (lens-input-source-observe)
   (let ((state (copy-tree lens-input-source-test-state)))
     (setf (plist-get state :frontmost_pid) 999)
     (lens-input-source-test-reply 'callbacks state))
   (should (= (length events) 1))
   (should-not lens-input-source--failed)
   (should-not lens-input-source--job)))

(ert-deftest lens-input-source-invalid-state-and-readback ()
  (lens-input-source-test-policy
   (setq focused (list 'frame 'chat-window 'chat 'chinese))
   (lens-input-source-observe)
   (lens-input-source-test-reply 'callbacks '(:bad t))
   (should lens-input-source--failed)
   (should (= (length events) 1)))
  (lens-input-source-test-policy
   (setq focused (list 'frame 'chat-window 'chat 'chinese))
   (lens-input-source-observe)
   (lens-input-source-test-reply 'callbacks)
   (lens-input-source-test-reply 'callbacks)
   (lens-input-source-test-reply 'callbacks)
   (should lens-input-source--failed)
   (should (= (length events) 3))))

(ert-deftest lens-input-source-interactive-selected-windows ()
  :tags '(input-source-interactive)
  (skip-unless (not noninteractive))
  ;; Real -nw selection/keyboard hooks, controlled system transport, no GUI/source mutation.
  (let ((lens-eglot-auto-start nil)
        (lens-input-source--seen :initial) (lens-input-source--desired nil)
        (lens-input-source--job nil) (lens-input-source--process nil)
        (lens-input-source--timer nil) (lens-input-source--failed nil)
        (lens-input-source--recent-chinese nil)
        (lens-input-source-english nil) (lens-input-source-chinese nil)
        events callbacks source chat notes)
    (unwind-protect
        (save-window-excursion
          (setq source (generate-new-buffer " *input-source-code-test*"))
          (setq chat (generate-new-buffer " *input-source-chat-test*"))
          (setq notes (generate-new-buffer " *input-source-notes-test*"))
          (with-current-buffer source
            (insert "let answer = 7\nlet more = answer + 1\n")
            (goto-char (point-min)) (tuareg-mode) (set-buffer-modified-p nil))
          (with-current-buffer chat (codex-ide-session-mode))
          (with-current-buffer notes (text-mode))
          (switch-to-buffer source) (delete-other-windows)
          (set-window-buffer (split-window-right) chat)
          (cl-letf (((symbol-function 'emacs-pid) (lambda () 123))
                    ((symbol-function 'lens-input-source-focused-p) (lambda () t))
                    ((symbol-function 'lens-input-source-start-request)
                     (lambda (arguments callback)
                       (push arguments events) (push callback callbacks)
                       (setq lens-input-source--process 'controlled)))
                    ((symbol-function 'lens-input-source-schedule)
                     (lambda () (unless lens-input-source--process (lens-input-source-pump)))))
            (lens-input-source-observe)
            (lens-input-source-test-reply 'callbacks)
            (execute-kbd-macro (kbd "C-n"))
            (should (= (length events) 1))
            (execute-kbd-macro (kbd "M-o"))
            (should (eq (current-buffer) chat))
            (should (= (length events) 2))
            (lens-input-source-test-reply 'callbacks)
            (should (equal (cadr (car events)) "com.apple.inputmethod.SCIM.ITABC"))
            (lens-input-source-test-reply 'callbacks)
            (let ((state (copy-tree lens-input-source-test-state)))
              (setf (plist-get state :current) "com.apple.inputmethod.SCIM.ITABC")
              (lens-input-source-test-reply 'callbacks state))
            (execute-kbd-macro (kbd "M-o"))
            (should (eq (current-buffer) source))
            (let ((state (copy-tree lens-input-source-test-state)))
              (setf (plist-get state :current) "com.apple.inputmethod.SCIM.ITABC")
              (lens-input-source-test-reply 'callbacks state))
            (should (equal (cadr (car events)) "com.apple.keylayout.ABC"))
            (lens-input-source-test-reply 'callbacks)
            (lens-input-source-test-reply 'callbacks)
            (let ((count (length events)))
              (with-current-buffer chat
                (let ((inhibit-read-only t)) (insert "controlled background update"))
                (lens-input-source-observe))
              (should (= (length events) count))
              (switch-to-buffer notes)
              (lens-input-source-observe)
              (should (= (length events) count)))
            (should-not lens-input-source--failed)
            (message "REAL terminal window/keyboard hooks Emacs=%s: source→chat→source, idle commands dedup, background/other buffers unchanged; system transport controlled"
                     emacs-version)))
      (dolist (buffer (list source chat notes))
        (when (buffer-live-p buffer)
          (with-current-buffer buffer (set-buffer-modified-p nil)) (kill-buffer buffer))))))
