;;; lsp-test.el --- Theme and real automatic LSP checks -*- lexical-binding: t; -*-
(load (expand-file-name "tests/review-test.el" lens-root) nil t)

(ert-deftest lens-automatic-lsp-defaults-and-theme ()
  (should (custom-theme-enabled-p 'modus-operandi-tinted))
  (should-not (custom-theme-enabled-p 'modus-vivendi))
  (should use-short-answers)
  (should (eq (key-binding (kbd "C-c j")) 'consult-ripgrep))
  (should lens-eglot-auto-start)
  (dolist (mode '(clojure-mode clojurescript-mode clojurec-mode clojure-ts-mode
                 clojurescript-ts-mode clojurec-ts-mode tuareg-mode caml-mode ocaml-ts-mode))
    (with-temp-buffer
      (setq major-mode mode)
      (should (member (lens-eglot-language) '(clojure ocaml)))
      (should (file-name-absolute-p (car (lens-eglot-contact nil))))
      (should (memq #'lens-auto-eglot (symbol-value (intern (format "%s-hook" mode)))))))
  (with-temp-buffer
    (setq buffer-file-name "/tmp/lens-pending.clj")
    (clojure-mode)
    (let ((before (copy-sequence post-command-hook)))
      (lens-auto-eglot)
      (should (equal before post-command-hook))))
  (with-temp-buffer
    (text-mode)
    (should-not (lens-eglot-language))))

(ert-deftest lens-real-automatic-language-servers ()
  (lens-test-project
   (let ((lens-eglot-auto-start t) (eglot-sync-connect 30)
         (eglot-connect-timeout 35) servers)
     ;; Source-only fixture avoids resolving dependencies or building an OCaml project.
     (make-directory "src/lens" t)
     (make-directory ".lsp" t)
     (with-temp-file "deps.edn" (insert "{:paths [\"src\"] :deps {}}\n"))
     (with-temp-file ".lsp/config.edn" (insert "{:source-paths [\"src\"] :project-specs []}\n"))
     (with-temp-file "src/lens/defs.clj" (insert "(ns lens.defs)\n(defn answer [x] (+ x 42))\n"))
     (with-temp-file "src/lens/core.clj" (insert "(ns lens.core (:require [lens.defs :as defs]))\n(def result (defs/answer 0))\n"))
     (with-temp-file ".merlin" (insert "S .\nB .\n"))
     (with-temp-file ml (insert "let answer x = x + 42\nlet result = answer 0\n"))
     (unwind-protect
         (dolist (case `((,(expand-file-name "src/lens/core.clj") "defs/answer" "src/lens/defs.clj")
                        (,ml "answer" "review.ml")))
           (switch-to-buffer (find-file-noselect (car case)))
           ;; Eglot's normal automatic hook defers startup until the first command.
           (run-hooks 'post-command-hook)
           (let ((deadline (+ (float-time) 40)))
             (while (and (not (bound-and-true-p eglot--managed-mode)) (< (float-time) deadline))
               (accept-process-output nil 0.1)))
           (should eglot--managed-mode)
           (should buffer-read-only)
           (should-not (delq t (copy-sequence before-save-hook)))
           (let* ((server (eglot-current-server))
                  (symbols (jsonrpc-request server :textDocument/documentSymbol
                                            (list :textDocument (eglot--TextDocumentIdentifier))))
                  (text (buffer-string)))
             (push server servers)
             (should (jsonrpc-running-p server))
             (should (> (length symbols) 0))
             (goto-char (point-max))
             (search-backward (cadr case))
             (let* ((backend (xref-find-backend))
                    (identifier (xref-backend-identifier-at-point backend))
                    (definitions (xref-backend-definitions backend identifier)))
               (should (eq backend 'eglot))
               (should definitions)
               (should (string-suffix-p (nth 2 case)
                                       (xref-file-location-file (xref-item-location (car definitions))))))
             (let ((origin (point)) (source (current-buffer))
                   (ocaml (eq (lens-eglot-language) 'ocaml)))
               (execute-kbd-macro "t")
               (with-current-buffer "*Code Lens Symbol*"
                 (should (string-match-p (if ocaml "int" "answer")
                                         (buffer-string))))
               (should (eq source (current-buffer)))
               (should (= origin (point)))
               (execute-kbd-macro "d")
               (should (string-suffix-p (nth 2 case) buffer-file-name))
               (execute-kbd-macro "b")
               (should (eq source (current-buffer)))
               (should (= origin (point)))
               (should (xref-backend-references 'eglot (lens-source-semantic-identifier)))

               (when (eq (lens-eglot-language) 'ocaml)
                 (with-temp-file "second.ml" (insert "let other = 7\n")))
               (switch-to-buffer (find-file-noselect
                                  (if (eq (lens-eglot-language) 'ocaml)
                                      (expand-file-name "second.ml" directory)
                                    (expand-file-name "src/lens/defs.clj" directory))))
               (run-hooks 'post-command-hook)
               (should (eq server (eglot-current-server)))
               (switch-to-buffer source))
             (should (equal text (buffer-string)))
             (message "REAL LSP %s: process=%S, document symbols=%d, xref definition=%s"
                      major-mode (process-command (jsonrpc--process server)) (length symbols) (nth 2 case))))
       (dolist (server (delete-dups servers))
         (when (jsonrpc-running-p server)
           (condition-case cleanup
               (with-current-buffer (car (eglot--managed-buffers server))
                 (eglot-shutdown server nil 3))
             (jsonrpc-error (message "Fixture cleanup: %s" (error-message-string cleanup))))))))))

(ert-deftest lens-source-single-key-scope-and-editing ()
  (let ((lens-eglot-auto-start nil))
    (with-temp-buffer
      (tuareg-mode)
      (should (eq (key-binding "t") 'lens-source-type))
      (should (eq (key-binding "d") 'lens-source-definition))
      (should (eq (key-binding "q") 'lens-source-quit))
      (should-error (lens-source-type) :type 'user-error)
      (read-only-mode -1)
      (should (eq (key-binding "t") 'self-insert-command))
      (insert "typed input")
      (read-only-mode 1)
      (should (eq (key-binding "t") 'lens-source-type))
      (lens-reading-mode -1)
      (should (eq (key-binding "d") 'self-insert-command))
      (should (equal (buffer-string) "typed input")))
    (with-temp-buffer
      (clojure-mode)
      (should (eq (key-binding "t") 'lens-source-type))
      (read-only-mode -1)
      (should (eq (key-binding "t") 'self-insert-command)))
    (with-temp-buffer
      (emacs-lisp-mode)
      (should (eq (key-binding "q") 'self-insert-command)))
    (with-temp-buffer
      (setq major-mode 'ocaml-ts-mode)
      (lens-reading-mode 1)
      (should (eq (key-binding "t") 'lens-source-type)))))

(ert-deftest lens-interactive-short-answers ()
  :tags '(interactive)
  (skip-unless (not noninteractive))
  (let ((map (make-sparse-keymap)) result)
    (define-key map (kbd "<f12>")
                (lambda () (interactive) (setq result (yes-or-no-p "Continue? "))))
    (let ((overriding-local-map map))
      (execute-kbd-macro (vconcat (kbd "<f12>") "y"))
      (should result)
      (execute-kbd-macro (vconcat (kbd "<f12>") "n"))
      (should-not result))))

(ert-deftest lens-interactive-reading-input-and-close ()
  :tags '(interactive)
  (skip-unless (not noninteractive))
  (lens-test-project
   (dolist (file (list clj ml))
     (switch-to-buffer (find-file-noselect file))
     ;; The same letter query is ordinary minibuffer input in both reading modes.
     (execute-kbd-macro (vconcat "/" "answer" (kbd "RET")))
     (should buffer-read-only)
     (let ((buffer (current-buffer)))
       (lens-reading-mode -1)
       (goto-char (point-max))
       (execute-kbd-macro "tdq")
       (should (string-suffix-p "tdq" (buffer-string)))
       (lens-reading-mode 1)
       (execute-kbd-macro "qn")
       (should (buffer-live-p buffer))
       (should (eq buffer (current-buffer)))
       (should (buffer-modified-p))
       ;; Only the fixture's unsaved test input is cleared before testing normal close.
       (set-buffer-modified-p nil)
       (execute-kbd-macro "q")
       (should-not (buffer-live-p buffer))))))
