;;; merlin-test.el --- Real Merlin type queries with Eglot -*- lexical-binding: t; -*-
(require 'ert)
(unless (ert-test-boundp 'lens-navigation-packages-and-header-compatibility)
  (load (expand-file-name "tests/navigation-display-test.el" lens-root) nil t))

(defconst lens-merlin-test-source
  "type count = int\nlet score : count = 7\nlet add x y = x + y\nlet result = add score (add 1 2)\n")

(ert-deftest lens-merlin-key-scope-and-help ()
  (lens-test-project
   (switch-to-buffer (find-file-noselect ml))
   (should (eq (key-binding "t") 'merlin-type-enclosing))
   (should (eq (key-binding "T") 'merlin-type-expr))
   (should (eq (key-binding "o") 'lens-toggle-ocaml-outline))
   (should-not (bound-and-true-p merlin-mode))
   (should-not (memq 'merlin-xref-backend xref-backend-functions))
   (should-not (memq 'merlin-completion-at-point completion-at-point-functions))
   (read-only-mode -1)
   (should (eq (key-binding "t") 'self-insert-command))
   (should (eq (key-binding "T") 'self-insert-command))
   (read-only-mode 1)
   (should (eq (key-binding "t") 'merlin-type-enclosing))
   (lens-reading-mode -1)
   (should (eq (key-binding "T") 'self-insert-command))
   (switch-to-buffer (find-file-noselect clj))
   (should (eq (key-binding "t") 'lens-source-type))
   (should (eq (key-binding "T") 'self-insert-command)))
  (let ((text (lens-help-text)))
    (dolist (command '(merlin-type-enclosing merlin-type-expr))
      (should (string-match-p (symbol-name command) text)))
    (should (string-match-p "C-<up>" text))
    (should (string-match-p "C-<down>" text)))
  (should (package-installed-p 'merlin))
  (should-not merlin--idle-timer)
  (should-not merlin-error-after-save))

(defun lens-merlin-test-key (key)
  "Run KEY through the actual map; use the terminal command loop when available."
  (if noninteractive
      (call-interactively (key-binding (kbd key)))
    (execute-kbd-macro (kbd key))))

(defun lens-merlin-test-type ()
  (with-current-buffer merlin-type-buffer-name
    (substring-no-properties (buffer-string))))

(defun lens-merlin-exercise-types ()
  "Check actual query output, native enclosing keys, file safety and live Eglot."
  (lens-test-project
   (let ((lens-eglot-auto-start t) (eglot-sync-connect 30)
         server (checks 0))
     (with-temp-file ".merlin" (insert "S .\nB .\n"))
     (with-temp-file ml (insert lens-merlin-test-source))
     (switch-to-buffer (find-file-noselect ml))
     (run-hooks 'post-command-hook)
     (setq server (eglot-current-server))
     (should (jsonrpc-running-p server))
     (unwind-protect
         (let ((source (current-buffer)) (text (buffer-string))
               (hooks (copy-sequence xref-backend-functions))
               (capfs (copy-sequence completion-at-point-functions))
               (disk (with-temp-buffer (insert-file-contents ml) (buffer-string))))
           (should (eq (xref-find-backend) 'eglot))
           ;; Repeated public command increases detail: the alias becomes int.
           (goto-char (point-min)) (search-forward "let result")
           (search-forward "score") (backward-char 2)
           (lens-merlin-test-key "t")
           (should (equal (lens-merlin-test-type) "count"))
           (should (= (cdr merlin--verbosity-cache) 0))
           (lens-merlin-test-key "t")
           (should (equal (lens-merlin-test-type) "int"))
           (should (= (cdr merlin--verbosity-cache) 1))
           (should-not (bound-and-true-p merlin-mode))
           ;; Native transient keys enlarge the true expression range, then shrink.
           (search-forward "add 1 2") (backward-char 3)
           (lens-merlin-test-key "t")
           (should (equal (lens-merlin-test-type) "int"))
           (let* ((small (cdr (nth merlin-enclosing-offset merlin-enclosing-types)))
                  (small-offset merlin-enclosing-offset))
             (should (= (- (cdr small) (car small)) 1))
             (should (eq (key-binding (kbd "C-<up>")) 'merlin-type-enclosing-go-up))
             (lens-merlin-test-key "C-<up>")
             (let* ((item (nth merlin-enclosing-offset merlin-enclosing-types))
                    (large (cdr item)))
               (should (stringp (car item)))
               (should (equal (lens-merlin-test-type) (car item)))
               (let ((overlay (cl-find-if (lambda (overlay)
                                           (eq (overlay-get overlay 'merlin-kind) 'highlight))
                                         (overlays-in (point-min) (point-max)))))
                 (should overlay)
                 (should (= (overlay-start overlay) (car large)))
                 (should (= (overlay-end overlay) (cdr large))))
               (should (> merlin-enclosing-offset small-offset))
               (should (<= (car large) (car small)))
               (should (>= (cdr large) (cdr small)))
               (should (> (- (cdr large) (car large)) (- (cdr small) (car small)))))
             (should (eq (key-binding (kbd "C-<down>")) 'merlin-type-enclosing-go-down))
             (lens-merlin-test-key "C-<down>")
             (should (= merlin-enclosing-offset small-offset))
             (should (equal (cdr (nth merlin-enclosing-offset merlin-enclosing-types)) small))
             ;; Every delayed layer must return/display a real type, up to the full call.
             (let (full-call)
               (while (< merlin-enclosing-offset (1- (length merlin-enclosing-types)))
                 (lens-merlin-test-key "C-<up>")
                 (let* ((item (nth merlin-enclosing-offset merlin-enclosing-types))
                        (expression (buffer-substring-no-properties (cadr item) (cddr item))))
                   (should (stringp (car item)))
                   (should (equal (lens-merlin-test-type) (car item)))
                   (when (string-match-p (regexp-quote "add score (add 1 2)") expression)
                     (should (string-prefix-p "int" (car item)))
                     (setq full-call t))))
               (should full-call))
             (while (> merlin-enclosing-offset small-offset)
               (lens-merlin-test-key "C-<down>"))
             (should (equal (cdr (nth merlin-enclosing-offset merlin-enclosing-types)) small)))
           ;; A contextual expression is queried through the real prompt in -nw.
           (if noninteractive
               (funcall (key-binding "T") "add score 5")
             (execute-kbd-macro (vconcat "Tadd score 5" (kbd "RET"))))
           (should (equal (lens-merlin-test-type) "int"))
           (should (eq (current-buffer) source))
           (should buffer-read-only)
           (should-not (buffer-modified-p))
           (should (equal text (buffer-string)))
           (should (equal disk (with-temp-buffer (insert-file-contents ml) (buffer-string))))
           ;; Neither query took over existing navigation, completion or diagnostics.
           (should (eq server (eglot-current-server)))
           (should (jsonrpc-running-p server))
           (should (equal hooks xref-backend-functions))
           (should (equal capfs completion-at-point-functions))
           (should-not (memq 'merlin-xref-backend xref-backend-functions))
           (should-not (memq 'merlin-completion-at-point completion-at-point-functions))
           (should-not merlin--idle-timer)
           (should-not merlin-error-after-save)
           (cl-letf (((symbol-function 'merlin-error-check)
                      (lambda (&rest _) (cl-incf checks))))
             (run-hooks 'after-save-hook)
             (save-buffer))
           (should (= checks 0))
           (goto-char (point-min)) (search-forward "let result") (search-forward "add")
           (backward-char 2)
           (let* ((identifier (lens-source-semantic-identifier))
                  (definitions (xref-backend-definitions 'eglot identifier)))
             (should definitions)
             (should (= (xref-file-location-line (xref-item-location (car definitions))) 3)))
           (let ((origin (point)))
             (lens-merlin-test-key "d")
             (should (= (line-number-at-pos) 3))
             (lens-merlin-test-key "b")
             (should (= (point) origin)))
           (should (xref-backend-references 'eglot (lens-source-semantic-identifier)))
           (read-only-mode -1)
           (should (eq (key-binding "t") 'self-insert-command))
           (should (eq (key-binding "T") 'self-insert-command))
           (goto-char (point-max))
           (if noninteractive (insert "tT") (execute-kbd-macro "tT"))
           (should (string-suffix-p "tT" (buffer-string)))
           (should (equal disk (with-temp-buffer (insert-file-contents ml) (buffer-string))))
           (set-buffer-modified-p nil)
           (read-only-mode 1)
           (should (eq (key-binding "t") 'merlin-type-enclosing))
           (lens-reading-mode -1)
           (should (eq (key-binding "T") 'self-insert-command))
           (message "REAL Merlin Emacs=%s terminal=%S: count→int repeated detail; 1-character→enclosing→1-character C-up/down; add score 5:int; disk unchanged; live Eglot definition/return/references; unlocked tT types"
                    emacs-version (not noninteractive)))
       (when server (lens-nav-shutdown server))))))

(ert-deftest lens-merlin-real-types-and-eglot ()
  (lens-merlin-exercise-types))

(ert-deftest lens-merlin-interactive-types-and-editing ()
  :tags '(merlin-interactive)
  (skip-unless (not noninteractive))
  (lens-merlin-exercise-types))

(ert-deftest lens-merlin-missing-explicit-binary ()
  (lens-test-project
   (switch-to-buffer (find-file-noselect ml))
   (let ((process-environment (cons "CODE_LENS_MERLIN=/no/such/ocamlmerlin" process-environment))
         (merlin-buffer-configuration nil)
         ;; Emacs 29 ERT enters the debugger for Merlin's (debug error) handler.
         ;; This check expects that error and must let the normal handler run.
         (debug-on-error nil))
     (let ((failure (should-error (merlin-type-enclosing) :type 'user-error)))
       (should (string-match-p "CODE_LENS_MERLIN" (error-message-string failure)))))))
