;;; navigation-display-test.el --- Scope and pulse integration -*- lexical-binding: t; -*-
(load (expand-file-name "tests/review-test.el" lens-root) nil t)
(require 'lens-navigation-display)

(ert-deftest lens-navigation-packages-and-header-compatibility ()
  (should (equal (package-desc-version (cadr (assq 'pulsar package-alist))) '(1 4 1)))
  (should (equal (package-desc-version (cadr (assq 'breadcrumb package-alist))) '(1 0 1)))
  (should (package-installed-p 'project '(0 9 8)))
  (should (string-match-p "Pulsar" (lens-help-text)))
  (should (string-match-p "Breadcrumb" (lens-help-text)))
  (lens-test-project
   (switch-to-buffer (find-file-noselect ml))
   (should lens-breadcrumb-mode)
   (should (equal header-line-format lens-breadcrumb-header))
   (should pulsar-mode)
   (imenu--make-index-alist t)
   (goto-char (point-min)) (search-forward "answer")
   (let ((header (lens-breadcrumb-header-text)))
     (should (string-match-p "\\[文本\\]" header))
     (should (string-match-p "answer" header))
     (should (<= (string-width header) (window-body-width))))
   ;; A long project path cannot consume the current definition's space.
   (let ((relative "long-project-directory-name/another-long-directory/deep/review.ml"))
     (make-directory (file-name-directory relative) t)
     (with-temp-file relative (insert "let answer x = x + 42\n"))
     (switch-to-buffer (find-file-noselect relative))
     (imenu--make-index-alist t)
     (search-forward "answer")
     (let ((header (lens-breadcrumb-header-text)))
       (should (string-match-p "answer" header))
       (should (<= (string-width header) (window-body-width)))))
   (lens-breadcrumb-mode -1)
   (setq-local header-line-format "Existing string header")
   (lens-breadcrumb-mode 1)
   (should-not lens-breadcrumb-mode)
   (should (equal header-line-format "Existing string header"))
   (setq-local header-line-format nil)
   (let ((which-function-mode t))
     (lens-breadcrumb-mode 1)
     (should-not lens-breadcrumb-mode)
     (should-not header-line-format))
   (setq imenu--index-alist '(("old" . 1)) breadcrumb--last-update-tick 42)
   (lens-breadcrumb-mode 1)
   (lens-breadcrumb-invalidate)
   (should-not imenu--index-alist)
   (should (= breadcrumb--last-update-tick -1)))
  (with-temp-buffer
    (setq buffer-file-name "/tmp/unrelated.el")
    (emacs-lisp-mode)
    (should-not lens-breadcrumb-mode)
    (should-not pulsar-mode)))

(ert-deftest lens-navigation-real-pulse-and-text-jumps ()
  (lens-test-project
   (switch-to-buffer (find-file-noselect ml))
   (goto-char (point-max))
   (let ((count 0) overlay
         (observer nil))
     (setq observer (lambda (&rest _)
                      (setq count (1+ count))
                      (setq overlay (cl-find-if (lambda (o) (overlay-get o 'pulse-delete))
                                                (overlays-at (line-beginning-position))))))
     (advice-add 'pulsar--create-pulse :after observer)
     (unwind-protect
         (progn
           (lens-pulse-reset)
           (lens-definition "answer")
           (should (= count 1))
           (should (overlayp overlay))
           (should (eq (overlay-buffer overlay) (current-buffer)))
           (lens-pulse-reset)
           (xref-go-back)
           (should (= count 2))
           (lens-pulse-reset)
           (should-error (lens-definition "missing-symbol") :type 'user-error)
           (should (= count 2))
           (goto-char (point-min))
           (forward-line 1)
           (let ((this-command 'next-line)) (run-hooks 'post-command-hook))
           (should (= count 2))
           (lens-pulse-reset)
           (consult--jump 5)
           (lens-pulse-successful-jump)
           (should (= count 3))
           (message "REAL pulse Emacs=%s: d/b/Consult 1 each, duplicate hook/movement/error 0; overlay=%S"
                    emacs-version (overlayp overlay)))
       (advice-remove 'pulsar--create-pulse observer)))))

(defconst lens-nav-ml
  "module Outer = struct\n  type color = Red | Blue\n  module Inner = struct\n    type record_t = { label : string; count : int }\n    type variant_t = Ready | Done of int\n    let shared x = let local = x + 1 in local\n\n    let worker (r : record_t) = r.count\n  end\n  module Second = struct\n    let shared x = x - 1\n  end\n  let outside = 0\nend\n\n\nlet top = Outer.outside\n")
(defconst lens-nav-mli
  "module Outer : sig\n  type color = Red | Blue\n  module Inner : sig\n    type record_t = { label : string; count : int }\n    type variant_t = Ready | Done of int\n    val shared : int -> int\n\n    val worker : record_t -> int\n  end\n  module Second : sig\n    val shared : int -> int\n  end\n  val outside : int\nend\n\n\nval top : int\n")

(defun lens-nav-expect (needle expected &optional after)
  "Check real native range crumbs and Code Lens's rendered header at NEEDLE."
  (goto-char (point-min))
  (when after (search-forward after))
  (search-forward needle)
  (let* ((breadcrumb-imenu-max-length 200)
         (scope (substring-no-properties (or (breadcrumb-imenu-crumbs) "")))
         (header (substring-no-properties (lens-breadcrumb-header-text))))
    (should (equal scope expected))
    (should (string-match-p (regexp-quote expected) header))
    (should-not (string-match-p "\\[文本\\]" header))
    (message "REAL scope %s at %s: %s; header=%s"
             (file-name-nondirectory buffer-file-name) needle scope header)))

(defun lens-nav-shutdown (server)
  "Close only the server created for this test's disposable project."
  (when (jsonrpc-running-p server)
    (when-let ((buffer (cl-find-if #'buffer-live-p (eglot--managed-buffers server))))
      (with-current-buffer buffer
        (condition-case cleanup
            (eglot-shutdown server nil 5)
          (jsonrpc-error (message "Fixture shutdown completed after timeout: %s"
                                  (error-message-string cleanup)))))))
  (should-not (jsonrpc-running-p server)))

(ert-deftest lens-navigation-real-semantic-scopes ()
  (lens-test-project
   (let ((lens-eglot-auto-start t) (eglot-sync-connect 30)
         (eglot-connect-timeout 35) servers)
     (make-directory "src/nav" t) (make-directory ".lsp" t)
     (with-temp-file ".merlin" (insert "S .\nB .\n"))
     (with-temp-file "deps.edn" (insert "{:paths [\"src\"] :deps {}}\n"))
     (with-temp-file ".lsp/config.edn" (insert "{:source-paths [\"src\"] :project-specs []}\n"))
     (with-temp-file "nested.ml" (insert lens-nav-ml))
     (with-temp-file "nested.mli" (insert lens-nav-mli))
     (with-temp-file "src/nav/core.clj"
       (insert "(ns nav.core)\n(defn alpha [x] (+ x 1))\n\n(defn beta [x] (* x 2))\n"))
     (unwind-protect
         (dolist (relative '("nested.ml" "nested.mli" "src/nav/core.clj"))
           (switch-to-buffer (find-file-noselect (expand-file-name relative directory)))
           (run-hooks 'post-command-hook)
           (let ((deadline (+ (float-time) 40)))
             (while (and (not (bound-and-true-p eglot--managed-mode)) (< (float-time) deadline))
               (accept-process-output nil 0.1)))
           (should eglot--managed-mode)
           (let ((server (eglot-current-server)))
             (push server servers)
             (let ((symbols (jsonrpc-request server :textDocument/documentSymbol
                                             (list :textDocument (eglot--TextDocumentIdentifier)))))
               (should (> (length symbols) 0)))
             (imenu--make-index-alist t)
             (should lens-breadcrumb-mode)
             (if (eq (lens-eglot-language) 'ocaml)
                 (progn
                   (lens-nav-expect "Outer" "Outer")
                   (lens-nav-expect "record_t" "Outer > Inner > record_t")
                   (lens-nav-expect "count : int" "Outer > Inner > record_t > count")
                   (lens-nav-expect "variant_t" "Outer > Inner > variant_t")
                   (lens-nav-expect "Done of int" "Outer > Inner > variant_t > Done")
                   (lens-nav-expect "shared" "Outer > Inner > shared")
                   (lens-nav-expect "shared" "Outer > Second > shared" "module Second")
                   (lens-nav-expect "worker" "Outer > Inner > worker")
                   (lens-nav-expect "outside" "Outer > outside")
                   (lens-nav-expect "top" "top")
                   ;; A blank line after shared stays inside Inner, not shared.
                   (goto-char (point-min)) (search-forward "shared")
                   (forward-line 1)
                   (should (equal (substring-no-properties (breadcrumb-imenu-crumbs))
                                  "Outer > Inner"))
                   ;; Outside the enclosing module's actual range, no preceding symbol guess.
                   (goto-char (point-min)) (search-forward "\nend\n")
                   (forward-line 1)
                   (should (equal (or (breadcrumb-imenu-crumbs) "") "")))
               (lens-nav-expect "nav.core" "nav.core")
               (lens-nav-expect "alpha" "alpha")
               (should (string-match-p "nav.core · alpha" (lens-breadcrumb-header-text)))
               (lens-nav-expect "beta" "beta")
               (should (string-match-p "nav.core · beta" (lens-breadcrumb-header-text)))
               (goto-char (point-min)) (search-forward "alpha") (forward-line 1)
               (should (equal (or (breadcrumb-imenu-crumbs) "") ""))
               (should (string-match-p "nav.core" (lens-breadcrumb-header-text)))
               (should buffer-read-only)
               (should-not (buffer-modified-p)))))
       (mapc #'lens-nav-shutdown (delete-dups servers))))))

(ert-deftest lens-navigation-interactive-success-cancel-and-movement ()
  :tags '(navigation-interactive)
  (skip-unless (not noninteractive))
  (lens-test-project
   (let ((lens-eglot-auto-start t) (eglot-sync-connect 30))
     (with-temp-file ".merlin" (insert "S .\nB .\n"))
     (with-temp-file ml (insert "let answer x = x + 42\nlet result = answer 0\n"))
     (switch-to-buffer (find-file-noselect ml))
     (run-hooks 'post-command-hook))
   (should eglot--managed-mode)
   (let ((count 0) observer (server (eglot-current-server)))
     (setq observer (lambda (&rest _) (setq count (1+ count))))
     (advice-add 'pulsar--create-pulse :after observer)
     (unwind-protect
         (progn
           (goto-char (point-max))
           (search-backward "answer")
           (execute-kbd-macro "d")
           (should (= count 1))
           (execute-kbd-macro "b")
           (should (= count 2))
           (execute-kbd-macro (kbd "C-n C-p"))
           (should (= count 2))
           (goto-char (point-max))
           (execute-kbd-macro (vconcat "i" "answer" (kbd "RET")))
           (should (looking-at-p "let answer"))
           (should (= count 3))
           (imenu--make-index-alist t)
           (should (string-match-p "answer" (lens-breadcrumb-header-text)))
           (lens-pulse-reset)
           (lens-test-select-minibuffer "#answer#review.clj" "review.clj" #'lens-consult-search)
           (should (equal buffer-file-name clj))
           (should (= count 4))
           (condition-case nil
               (execute-kbd-macro (vconcat (kbd "C-s") "answer" (kbd "C-g")))
             (quit nil))
           (should (= count 4))
           (should buffer-read-only)
           (message "REAL terminal Emacs=%s d/b/i/rg one pulse each; C-n/C-p/cancel zero; header updated"
                    emacs-version))
       (advice-remove 'pulsar--create-pulse observer)
       (lens-nav-shutdown server)))))
