;;; ocaml-outline-test.el --- Repo-owned outline, scope and isolation checks -*- lexical-binding: t; -*-
(require 'ert)
(unless (ert-test-boundp 'lens-navigation-packages-and-header-compatibility)
  (load (expand-file-name "tests/navigation-display-test.el" lens-root) nil t))
(require 'lens-ocaml-outline)

(ert-deftest lens-outline-key-scope-and-no-server ()
  (lens-test-project
   (switch-to-buffer (find-file-noselect ml))
   (should (eq (key-binding "o") 'lens-toggle-ocaml-outline))
   (should lens-ocaml-outline-keys-mode)
   (let ((error (should-error (lens-toggle-ocaml-outline) :type 'user-error)))
     (should (string-match-p "C-c r s" (error-message-string error))))
   (should-not ocaml-outline-buffer)
   (read-only-mode -1)
   (should (eq (key-binding "o") 'self-insert-command))
   (read-only-mode 1)
   (should (eq (key-binding "o") 'lens-toggle-ocaml-outline))
   (lens-reading-mode -1)
   (should (eq (key-binding "o") 'self-insert-command))
   (lens-reading-mode 1)
   (lens-source-reading-keys-mode -1)
   (should (eq (key-binding "o") 'self-insert-command))
   (switch-to-buffer (find-file-noselect clj))
   (should-not lens-ocaml-outline-keys-mode)
   (should (eq (key-binding "o") 'self-insert-command))
   (should (eq (key-binding "d") 'lens-source-definition)))
  (should (string-match-p "o .*仅 OCaml" (lens-help-text))))

(ert-deftest lens-outline-repository-owned-loads ()
  (dolist (library '("lens-review" "lens-lsp" "lens-source-reading" "lens-codex"
                     "lens-navigation-display" "lens-ocaml-outline" "ocaml-outline" "lens-help"))
    (should (file-in-directory-p (file-truename (locate-library library)) lens-root)))
  (let* ((builtin-root (file-truename (expand-file-name ".." data-directory)))
         (outside (cl-loop for item in load-history
                           for file = (car item)
                           when (and (stringp file) (file-name-absolute-p file)
                                     (not (file-in-directory-p (file-truename file) lens-root))
                                     (not (file-in-directory-p (file-truename file) builtin-root)))
                           collect file)))
    (should-not outside)
    (message "LOAD AUDIT Emacs=%s: all loaded Elisp is Emacs distribution or repo-owned/locked package source; HOME=%s"
             emacs-version (getenv "HOME"))))

(defun lens-outline-entry (outline name)
  (with-current-buffer outline
    (cl-find name ocaml-outline--entries :test #'equal :key (lambda (e) (plist-get e :name)))))

(defun lens-outline-check (relative)
  "Exercise real ranges, source following, buttons, folds, refresh and windows."
  (switch-to-buffer (find-file-noselect relative))
  (run-hooks 'post-command-hook)
  (should eglot--managed-mode)
  ;; Outline still receives rich ranges with Breadcrumb deliberately disabled.
  (lens-breadcrumb-mode -1)
  (let* ((source (current-buffer)) (text (buffer-string))
         (source-window (selected-window))
         (window (ocaml-outline))
         (outline (window-buffer window))
         (worker (lens-outline-entry outline "worker")))
    (should (eq (window-parameter window 'window-side) 'right))
    (should (eq source (current-buffer)))
    (should (eq (selected-window) source-window))
    (should (equal (plist-get (plist-get worker :parent) :name) "Inner"))
    (with-current-buffer outline
      (should (derived-mode-p 'ocaml-outline-mode))
      (should buffer-read-only)
      (should (eq source ocaml-outline-source-buffer))
      (let ((duplicates (cl-remove-if-not (lambda (e) (equal (plist-get e :name) "shared"))
                                         ocaml-outline--entries)))
        (should (= (length duplicates) 2))
        (should (equal (mapcar (lambda (e) (plist-get (plist-get e :parent) :name)) duplicates)
                       '("Inner" "Second")))
        (should-not (= (marker-position (plist-get (car duplicates) :source-beg))
                       (marker-position (plist-get (cadr duplicates) :source-beg)))))
      (should (markerp (plist-get (lens-outline-entry outline "count") :source-beg)))
      (should (markerp (plist-get (lens-outline-entry outline "Done") :source-end))))
    ;; Source movement expands the actual path and highlights the current leaf.
    (goto-char (point-min)) (search-forward "worker")
    (run-hooks 'post-command-hook)
    (with-current-buffer outline
      (should (equal (plist-get ocaml-outline--current-entry :name) "worker"))
      (should (overlayp ocaml-outline--highlight-overlay)))
    ;; Native disclosure toggling and button jump retain the original behavior.
    (select-window window)
    (let ((outer (lens-outline-entry outline "Outer")))
      (goto-char (plist-get outer :toggle-marker))
      (ocaml-outline-toggle)
      (should (ocaml-outline--entry-collapsed-p outer))
      (ocaml-outline-toggle)
      (should-not (ocaml-outline--entry-collapsed-p outer)))
    (goto-char (plist-get worker :outline-beg))
    (button-activate (next-button (point)))
    (should (eq source (current-buffer)))
    (should (eq source-window (selected-window)))
    (should (= (point) (marker-position (plist-get worker :source-beg))))
    (should buffer-read-only)
    (should (equal text (buffer-string)))
    (should-not (buffer-modified-p))
    (with-current-buffer outline (ocaml-outline-refresh))
    (ocaml-outline)
    (should (= 1 (cl-count #'ocaml-outline--sync post-command-hook)))
    ;; q closes the side window. Killing the outline removes its source hook.
    (select-window (get-buffer-window outline))
    (quit-window)
    (should-not (get-buffer-window outline))
    (switch-to-buffer source)
    (kill-buffer outline)
    (should-not ocaml-outline-buffer)
    (should-not (memq #'ocaml-outline--sync post-command-hook))
    (should buffer-read-only)
    (message "REAL outline Emacs=%s file=%s: nested ranges, same-name scopes, follow/fold/jump/refresh/close, source read-only"
             emacs-version relative)))

(ert-deftest lens-outline-real-language-server ()
  (lens-test-project
   (let ((lens-eglot-auto-start t) (eglot-sync-connect 30) servers)
     (with-temp-file ".merlin" (insert "S .\nB .\n"))
     (with-temp-file "nested.ml" (insert lens-nav-ml))
     (with-temp-file "nested.mli" (insert lens-nav-mli))
     (unwind-protect
         (dolist (relative '("nested.ml" "nested.mli"))
           (switch-to-buffer (find-file-noselect relative))
           (run-hooks 'post-command-hook)
           (push (eglot-current-server) servers)
           (lens-outline-check relative))
       (mapc #'lens-nav-shutdown (delete-dups (delq nil servers)))))))

(ert-deftest lens-outline-interactive-o-ret-q-and-editing ()
  :tags '(outline-interactive)
  (skip-unless (not noninteractive))
  (lens-test-project
   (let ((lens-eglot-auto-start t) (eglot-sync-connect 30) server outline)
     (with-temp-file ".merlin" (insert "S .\nB .\n"))
     (with-temp-file ml (insert lens-nav-ml))
     (switch-to-buffer (find-file-noselect ml))
     (run-hooks 'post-command-hook)
     (setq server (eglot-current-server))
     (unwind-protect
         (let ((source (current-buffer)) (text (buffer-string)))
           (execute-kbd-macro "o")
           (setq outline ocaml-outline-buffer)
           (should (buffer-live-p outline))
           (should (eq source (current-buffer)))
           (select-window (get-buffer-window outline))
           (let ((worker (lens-outline-entry outline "worker")))
             (ocaml-outline--reveal-entry worker)
             (goto-char (plist-get worker :outline-beg))
             (goto-char (button-start (next-button (point))))
             (execute-kbd-macro (kbd "RET"))
             (should (eq source (current-buffer)))
             (should (= (point) (marker-position (plist-get worker :source-beg)))))
           (should buffer-read-only)
           (should (equal text (buffer-string)))
           (select-window (get-buffer-window outline))
           (execute-kbd-macro "gq")
           (should-not (get-buffer-window outline))
           (switch-to-buffer source)
           (read-only-mode -1)
           (goto-char (point-max))
           (execute-kbd-macro "o")
           (should (= (char-before) ?o))
           (set-buffer-modified-p nil)
           (message "REAL outline terminal Emacs=%s: o opens, RET jumps, g refreshes, q closes, unlocked o types"
                    emacs-version))
       (when (buffer-live-p outline) (kill-buffer outline))
       (when server (lens-nav-shutdown server))))))

(ert-deftest lens-outline-interactive-toggle-focus-and-multiple-sources ()
  :tags '(outline-interactive)
  (skip-unless (not noninteractive))
  (lens-test-project
   (let ((lens-eglot-auto-start t) (eglot-sync-connect 30)
         server outline-a outline-b notes)
     (with-temp-file ".merlin" (insert "S .\nB .\n"))
     (with-temp-file ml (insert lens-nav-ml))
     (with-temp-file "second.ml" (insert "let second_answer x = x + 7\n"))
     (switch-to-buffer (find-file-noselect ml))
     (run-hooks 'post-command-hook)
     (setq server (eglot-current-server))
     (unwind-protect
         (let* ((source-a (current-buffer)) (text-a (buffer-string))
                (window-a (selected-window))
                (source-b (find-file-noselect "second.ml"))
                (text-b (with-current-buffer source-b (buffer-string))))
           ;; Open and close from source, then reopen the same associated buffer.
           (execute-kbd-macro "o")
           (setq outline-a ocaml-outline-buffer)
           (should (get-buffer-window outline-a))
           (should (eq source-a (current-buffer)))
           (execute-kbd-macro "o")
           (should-not (get-buffer-window outline-a))
           (should (eq window-a (selected-window)))
           (execute-kbd-macro "o")
           (should (eq outline-a ocaml-outline-buffer))
           (select-window (get-buffer-window outline-a))
           (should (eq (key-binding "o") 'lens-toggle-ocaml-outline))
           (execute-kbd-macro "o")
           (should-not (get-buffer-window outline-a))
           (should (eq source-a (current-buffer)))
           (should (eq window-a (selected-window)))
           ;; Preserve an unrelated notes window while toggling two real sources.
           (setq notes (get-buffer-create " *outline-toggle-test-notes*"))
           (let* ((notes-window (split-window window-a nil 'below))
                  (window-b (split-window window-a nil 'right)))
             (set-window-buffer notes-window notes)
             (set-window-buffer window-b source-b)
             (select-window window-b)
             (run-hooks 'post-command-hook)
             (should (eq server (eglot-current-server)))
             (execute-kbd-macro "o")
             (setq outline-b ocaml-outline-buffer)
             (should (get-buffer-window outline-b))
             ;; A is hidden while B owns the native shared side slot: o opens A.
             (select-window window-a)
             (execute-kbd-macro "o")
             (should (get-buffer-window outline-a))
             (should-not (get-buffer-window outline-b))
             (should (eq (window-buffer window-b) source-b))
             ;; Show B's outline in its own ordinary window as a second visible outline.
             (set-window-buffer window-b outline-b)
             (execute-kbd-macro "o")
             (should-not (get-buffer-window outline-a))
             (should (eq (window-buffer window-b) outline-b))
             (should (window-live-p notes-window))
             (should (eq (window-buffer notes-window) notes))
             ;; Closing a focused B outline returns to B even when its source was hidden.
             (select-window window-b)
             (execute-kbd-macro "o")
             (should-not (get-buffer-window outline-b))
             (should (eq (current-buffer) source-b))
             (should (window-live-p notes-window))
             (should (eq (window-buffer notes-window) notes))
             ;; A side outline with a hidden source creates a safe return pane.
             (select-window window-a)
             (execute-kbd-macro "o")
             (set-window-buffer window-a source-b)
             (select-window (get-buffer-window outline-a))
             (execute-kbd-macro "o")
             (should-not (get-buffer-window outline-a))
             (should (eq (current-buffer) source-a))
             (should (eq (window-buffer window-b) source-b))
             (should (window-live-p notes-window))
             (should (eq (window-buffer notes-window) notes)))
           ;; A sole ordinary outline window is restored to the source rather than deleted.
           (switch-to-buffer source-a)
           (delete-other-windows)
           (set-window-buffer (selected-window) outline-a)
           (execute-kbd-macro "o")
           (should (eq source-a (current-buffer)))
           (should (one-window-p))
           ;; q retains the original behavior, and unlocking still types o.
           (execute-kbd-macro "o")
           (select-window (get-buffer-window outline-a))
           (should (eq (key-binding "q") 'quit-window))
           (execute-kbd-macro "q")
           (switch-to-buffer source-a)
           (should buffer-read-only)
           (should (equal text-a (buffer-string)))
           (with-current-buffer source-b
             (should buffer-read-only)
             (should (equal text-b (buffer-string))))
           (read-only-mode -1)
           (goto-char (point-max))
           (execute-kbd-macro "o")
           (should (= (char-before) ?o))
           (set-buffer-modified-p nil)
           (read-only-mode 1)
           (lens-reading-mode -1)
           (should (eq (key-binding "o") 'self-insert-command))
           (message "REAL outline toggle Emacs=%s: source open/close, focused close/back, two sources, other outline/notes preserved, hidden-source side pane, sole window, q and modeoff"
                    emacs-version))
       (dolist (outline (list outline-a outline-b))
         (when (buffer-live-p outline) (kill-buffer outline)))
       (when (buffer-live-p notes) (kill-buffer notes))
       (when server (lens-nav-shutdown server))))))
