;;; review-test.el --- Review integration tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'project)
(require 'xref)
(require 'imenu)

(defconst lens-test-root
  (file-name-directory (directory-file-name
                        (file-name-directory (or load-file-name buffer-file-name)))))
(defmacro lens-test-project (&rest body)
  "Run BODY in a disposable Git project with both review languages."
  `(let* ((directory (make-temp-file "lens-project-" t))
          (default-directory (file-name-as-directory directory))
          (project-list-file (expand-file-name "projects" directory))
          (clj (expand-file-name "review.clj" directory))
          (ml (expand-file-name "review.ml" directory)))
     (unwind-protect
         (progn
           (with-temp-file clj (insert "(ns review)\n(defn answer [x]\n  (+ x 42))\n"))
           (with-temp-file ml (insert "let answer x =\n  x + 42\n"))
           (should (zerop (call-process "git" nil nil nil "init" "-q")))
           (call-process "git" nil nil nil "add" ".")
           (should (zerop (call-process "git" nil nil nil "-c" "user.name=Code Lens Tests"
                                       "-c" "user.email=tests@example.invalid" "commit" "-qm" "fixture")))
           ,@body)
       (dolist (b (buffer-list))
         (when-let ((file (buffer-file-name b)))
           (when (string-prefix-p directory file)
             (with-current-buffer b (set-buffer-modified-p nil))
             (kill-buffer b))))
       (delete-directory directory t))))

(ert-deftest lens-isolated-runtime ()
  (should (string-prefix-p (expand-file-name ".local/" lens-test-root)
                           (expand-file-name user-emacs-directory)))
  (should (string-prefix-p user-emacs-directory package-user-dir))
  (should (string-prefix-p user-emacs-directory custom-file))
  (should-not enable-local-eval)
  (should-not (memq 'eglot-ensure prog-mode-hook)))

(ert-deftest lens-code-read-only-unlock-and-disk-safety ()
  (lens-test-project
   (with-current-buffer (find-file-noselect clj)
     (should (eq major-mode 'clojure-mode))
     (should buffer-read-only)
     (should-error (insert "oops") :type 'buffer-read-only)
     (read-only-mode -1)
     (should-not buffer-read-only)
     (insert "temporary")
     (set-buffer-modified-p nil))
   (should (string= "" (with-temp-buffer
                         (call-process "git" nil t nil "diff" "--") (buffer-string))))))

(ert-deftest lens-language-structure-and-index ()
  (lens-test-project
   (dolist (pair `((,clj . clojure-mode) (,ml . tuareg-mode)))
     (with-current-buffer (find-file-noselect (car pair))
       (should (eq major-mode (cdr pair)))
       (should buffer-read-only)
       (should outline-minor-mode)
       (should (cl-some (lambda (entry) (equal (car entry) "answer"))
                        (imenu--make-index-alist t)))
       (goto-char (point-max))
       (beginning-of-defun)
       (should (< (point) (point-max)))
       (should (looking-at-p outline-regexp))
       (font-lock-ensure)
       (should (text-property-not-all (point-min) (point-max) 'face nil))))
   (with-current-buffer (find-file-noselect clj)
     (goto-char (point-min))
     (forward-sexp)
     (should (= (char-before) ?\))))))

(ert-deftest lens-project-search-and-xref-return ()
  (lens-test-project
   (with-current-buffer (find-file-noselect clj)
     (should (member clj (project-files (project-current t))))
     (should (fboundp 'lens-search))
     (should (eq (key-binding (kbd "C-c r /")) 'lens-search))
     (let* ((buffer (lens-search "answer"))
            (process (get-buffer-process buffer))
            (deadline (+ (float-time) 8)))
       (while (and (process-live-p process) (< (float-time) deadline))
         (accept-process-output process 0.05))
       (should (= (process-exit-status process) 0))
       (with-current-buffer buffer
         (should (string-match-p "review.clj:[0-9]+:[0-9]+:" (buffer-string)))
         (should (string-match-p "review.ml:[0-9]+:[0-9]+:" (buffer-string)))))
     (let* ((project (project-current t))
            (items (xref-matches-in-files "answer" (project-files project))))
       (should (= 2 (length items)))
       (goto-char (point-max))
       (let ((origin (point)))
         (should (fboundp 'lens-definition))
         (lens-definition "answer")
         (should (< (point) origin))
         (xref-go-back)
         (should (= (point) origin)))
       (goto-char (point-min))
       (xref-push-marker-stack)
       (find-file ml)
       (xref-go-back)
       (should (equal (buffer-file-name) clj))
       (should (= (point) (point-min)))))))

(ert-deftest lens-magit-status-log-blame-diff-and-staging ()
  (lens-test-project
   (should (require 'magit nil t))
   (let* ((status (magit-status-setup-buffer default-directory))
          (head (magit-git-string "rev-parse" "HEAD")))
     (with-current-buffer status
       (should (derived-mode-p 'magit-status-mode))
       (should-not (bound-and-true-p lens-reading-mode)))
     (with-current-buffer (magit-log-setup-buffer '("HEAD") nil nil)
       (should (derived-mode-p 'magit-log-mode)))
     (switch-to-buffer (find-file-noselect clj))
     (magit-blame-addition nil)
     (let ((deadline (+ (float-time) 8)))
       (while (and (bound-and-true-p magit-blame-process) (< (float-time) deadline))
         (accept-process-output nil 0.05)))
     (should magit-blame-mode)
     (should (magit-blame-chunk-at (point-min)))
     (magit-blame-quit)
     (with-temp-file ml (insert "let answer x =\n  x + 43\n"))
     (with-current-buffer (magit-diff-setup-buffer nil nil nil nil)
       (should (derived-mode-p 'magit-diff-mode))
       (should (save-excursion (goto-char (point-min)) (search-forward "43" nil t)))
       (goto-char (point-min))
       (magit-section-forward)
       (should (> (point) (point-min)))
       (let ((limit 10))
         (while (and (> limit 0) (not (magit-hunk-section-p (magit-current-section))))
           (magit-section-forward)
           (setq limit (1- limit))))
       (should (magit-hunk-section-p (magit-current-section))))
     ;; Exercise the real Magit write primitive only in this disposable repository.
     (magit-call-git "add" "--" "review.ml")
     (should (string-match-p "review.ml" (magit-git-string "diff" "--cached" "--name-only")))
     (should (equal head (magit-git-string "rev-parse" "HEAD"))))))

(ert-deftest lens-no-automatic-eglot-or-formatting ()
  (lens-test-project
   (with-current-buffer (find-file-noselect ml)
     (should (eq (key-binding (kbd "C-c r s")) 'lens-semantic-navigation))
     (should-not (bound-and-true-p eglot--managed-mode))
     (should-not before-save-hook)
     (should-not (file-exists-p (expand-file-name ".lens-tags" default-directory)))
     (let ((exec-path nil))
       (should-error (lens-semantic-navigation) :type 'user-error)))))
