;;; review-test.el --- Review integration tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'project)
(require 'xref)
(require 'imenu)

(defconst lens-test-root
  (file-name-directory (directory-file-name
                        (file-name-directory (or load-file-name buffer-file-name)))))
(defmacro lens-test-project (&rest body)
  "Run BODY in a disposable Git project with both review languages."
  `(let* ((directory (make-temp-file "lens-project-" t))
          (default-directory (file-name-as-directory directory))
          (project-list-file (expand-file-name "projects" directory))
          (clj (expand-file-name "review.clj" directory))
          (ml (expand-file-name "review.ml" directory)))
     (unwind-protect
         (progn
           (with-temp-file clj (insert "(ns review)\n(defn answer [x]\n  (+ x 42))\n"))
           (with-temp-file ml (insert "let answer x =\n  x + 42\n"))
           (should (zerop (call-process "git" nil nil nil "init" "-q")))
           (call-process "git" nil nil nil "add" ".")
           (should (zerop (call-process "git" nil nil nil "-c" "user.name=Code Lens Tests"
                                       "-c" "user.email=tests@example.invalid" "commit" "-qm" "fixture")))
           ,@body)
       (dolist (b (buffer-list))
         (when-let ((file (buffer-file-name b)))
           (when (string-prefix-p directory file)
             (with-current-buffer b (set-buffer-modified-p nil))
             (kill-buffer b))))
       (delete-directory directory t))))

(ert-deftest lens-isolated-runtime ()
  (should (string-prefix-p (expand-file-name ".local/" lens-test-root)
                           (expand-file-name user-emacs-directory)))
  (should (string-prefix-p user-emacs-directory package-user-dir))
  (should (string-prefix-p user-emacs-directory custom-file))
  (should-not enable-local-eval)
  (should-not (memq 'eglot-ensure prog-mode-hook)))

(ert-deftest lens-code-read-only-unlock-and-disk-safety ()
  (lens-test-project
   (with-current-buffer (find-file-noselect clj)
     (should (eq major-mode 'clojure-mode))
     (should buffer-read-only)
     (should-error (insert "oops") :type 'buffer-read-only)
     (read-only-mode -1)
     (should-not buffer-read-only)
     (insert "temporary")
     (set-buffer-modified-p nil))
   (should (string= "" (with-temp-buffer
                         (call-process "git" nil t nil "diff" "--") (buffer-string))))))

(ert-deftest lens-language-structure-and-index ()
  (lens-test-project
   (dolist (pair `((,clj . clojure-mode) (,ml . tuareg-mode)))
     (with-current-buffer (find-file-noselect (car pair))
       (should (eq major-mode (cdr pair)))
       (should buffer-read-only)
       (should outline-minor-mode)
       (should (cl-some (lambda (entry) (equal (car entry) "answer"))
                        (imenu--make-index-alist t)))
       (goto-char (point-max))
       (beginning-of-defun)
       (should (< (point) (point-max)))
       (should (looking-at-p outline-regexp))
       (font-lock-ensure)
       (should (text-property-not-all (point-min) (point-max) 'face nil))))
   (with-current-buffer (find-file-noselect clj)
     (goto-char (point-min))
     (forward-sexp)
     (should (= (char-before) ?\))))))

(ert-deftest lens-project-search-and-xref-return ()
  (lens-test-project
   (with-current-buffer (find-file-noselect clj)
     (should (member clj (project-files (project-current t))))
     (should (fboundp 'lens-search))
     (should (eq (key-binding (kbd "C-c r G")) 'lens-search))
     (let* ((buffer (lens-search "answer"))
            (process (get-buffer-process buffer))
            (deadline (+ (float-time) 8)))
       (while (and (process-live-p process) (< (float-time) deadline))
         (accept-process-output process 0.05))
       (should (= (process-exit-status process) 0))
       (with-current-buffer buffer
         (should (string-match-p "review.clj:[0-9]+:[0-9]+:" (buffer-string)))
         (should (string-match-p "review.ml:[0-9]+:[0-9]+:" (buffer-string)))))
     (let* ((project (project-current t))
            (items (xref-matches-in-files "answer" (project-files project))))
       (should (= 2 (length items)))
       (goto-char (point-max))
       (let ((origin (point)))
         (should (fboundp 'lens-definition))
         (lens-definition "answer")
         (should (< (point) origin))
         (xref-go-back)
         (should (= (point) origin)))
       (goto-char (point-min))
       (xref-push-marker-stack)
       (find-file ml)
       (xref-go-back)
       (should (equal (buffer-file-name) clj))
       (should (= (point) (point-min)))))))

(ert-deftest lens-magit-status-log-blame-diff-and-staging ()
  (lens-test-project
   (should (require 'magit nil t))
   (let* ((status (magit-status-setup-buffer default-directory))
          (head (magit-git-string "rev-parse" "HEAD")))
     (with-current-buffer status
       (should (derived-mode-p 'magit-status-mode))
       (should-not (bound-and-true-p lens-reading-mode)))
     (with-current-buffer (magit-log-setup-buffer '("HEAD") nil nil)
       (should (derived-mode-p 'magit-log-mode)))
     (switch-to-buffer (find-file-noselect clj))
     (magit-blame-addition nil)
     (let ((deadline (+ (float-time) 8)))
       (while (and (bound-and-true-p magit-blame-process) (< (float-time) deadline))
         (accept-process-output nil 0.05)))
     (should magit-blame-mode)
     (should (magit-blame-chunk-at (point-min)))
     (magit-blame-quit)
     (with-temp-file ml (insert "let answer x =\n  x + 43\n"))
     (with-current-buffer (magit-diff-setup-buffer nil nil nil nil)
       (should (derived-mode-p 'magit-diff-mode))
       (should (save-excursion (goto-char (point-min)) (search-forward "43" nil t)))
       (goto-char (point-min))
       (magit-section-forward)
       (should (> (point) (point-min)))
       (let ((limit 10))
         (while (and (> limit 0) (not (magit-hunk-section-p (magit-current-section))))
           (magit-section-forward)
           (setq limit (1- limit))))
       (should (magit-hunk-section-p (magit-current-section))))
     ;; Exercise the real Magit write primitive only in this disposable repository.
     (magit-call-git "add" "--" "review.ml")
     (should (string-match-p "review.ml" (magit-git-string "diff" "--cached" "--name-only")))
     (should (equal head (magit-git-string "rev-parse" "HEAD"))))))

(ert-deftest lens-no-automatic-eglot-or-formatting ()
  (lens-test-project
   (with-current-buffer (find-file-noselect ml)
     (should (eq (key-binding (kbd "C-c r s")) 'lens-semantic-navigation))
     (should-not (bound-and-true-p eglot--managed-mode))
     (should-not before-save-hook)
     (should-not (file-exists-p (expand-file-name ".lens-tags" default-directory)))
     (let ((exec-path nil))
       (should-error (lens-semantic-navigation) :type 'user-error)))))

(defmacro lens-test-scratch (&rest body)
  "Run BODY with a fresh scratch buffer without disturbing the original."
  `(let ((original (get-buffer "*scratch*")) scratch)
     (when original
       (with-current-buffer original
         (rename-buffer (generate-new-buffer-name " *lens-original-scratch*"))))
     (unwind-protect
         (progn
           (setq scratch (get-buffer-create "*scratch*"))
           (with-current-buffer scratch ,@body))
       (when (buffer-live-p scratch)
         (with-current-buffer scratch (set-buffer-modified-p nil))
         (kill-buffer scratch))
       (when (buffer-live-p original)
         (with-current-buffer original (rename-buffer "*scratch*"))))))

(ert-deftest lens-scratch-default-startup-guide ()
  (should (stringp initial-scratch-message))
  (with-current-buffer (get-buffer "*scratch*")
    (should (string-match-p "Code Lens" (buffer-string)))
    (should (eq major-mode 'text-mode))
    (should-not buffer-read-only)
    (should-not (buffer-modified-p)))
  (lens-test-scratch
   (should (fboundp 'lens-initialize-scratch))
   (lens-initialize-scratch)
   (should (equal (buffer-string) initial-scratch-message))
   (should (eq major-mode 'text-mode))
   (should-not (buffer-modified-p))
   (should (string-match-p "只读" (buffer-string)))
   (should (string-match-p "手动" (buffer-string)))
   (should (string-match-p "当前文件" (buffer-string)))
   (should (string-match-p "bin/code-lens -nw" (buffer-string)))))

(ert-deftest lens-scratch-guide-covers-installed-bindings ()
  (should (fboundp 'lens-help-text))
  (let ((text (lens-help-text)))
    (map-keymap
     (lambda (event binding)
       (when (and (commandp binding)
                  (not (string-prefix-p "magit-" (symbol-name binding))))
         (should (string-match-p
                  (regexp-quote (concat "C-c r " (key-description (vector event)))) text))
         (should (string-match-p (regexp-quote (symbol-name binding)) text))))
     lens-review-map)
    (dolist (key '("M-." "M-," "M-o" "C-c <left>" "C-c <right>"))
      (should (string-match-p (regexp-quote key) text))
      (should (string-match-p
               (regexp-quote (symbol-name (keymap-lookup (current-global-map) key))) text)))
    (should-not (string-match-p "未绑定" text))))

(ert-deftest lens-scratch-guide-reflects-current-keymap ()
  (should (fboundp 'lens-help-text))
  (let ((old (keymap-lookup lens-review-map "/")))
    (unwind-protect
        (progn
          (keymap-set lens-review-map "/" #'ignore)
          (should (string-match-p "C-c r /.*ignore" (lens-help-text))))
      (keymap-set lens-review-map "/" old))))

(ert-deftest lens-scratch-reload-preserves-user-content ()
  (should (fboundp 'lens-initialize-scratch))
  (lens-test-scratch
   (emacs-lisp-mode)
   (read-only-mode -1)
   (insert "; 我的笔记\n(+ 1 2)\n")
   (goto-char 5)
   (let ((text (buffer-string)) (position (point)) (mode major-mode))
     (read-only-mode 1)
     (load (expand-file-name "lisp/lens-review.el" lens-test-root) nil t)
     (load (expand-file-name "init.el" lens-test-root) nil t)
     (should (equal text (buffer-string)))
     (should (= position (point)))
     (should (eq major-mode mode))
     (should buffer-read-only)
     (should (buffer-modified-p)))))

(ert-deftest lens-scratch-preserves-modified-empty-and-whitespace ()
  (should (fboundp 'lens-initialize-scratch))
  (lens-test-scratch
   (set-buffer-modified-p t)
   (lens-initialize-scratch)
   (should (zerop (buffer-size)))
   (should (buffer-modified-p)))
  (lens-test-scratch
   (insert " \n")
   (set-buffer-modified-p nil)
   (lens-initialize-scratch)
   (should (equal " \n" (buffer-string))))
  (lens-test-scratch
   (read-only-mode 1)
   (lens-initialize-scratch)
   (should (zerop (buffer-size)))
   (should buffer-read-only)))

(ert-deftest lens-help-refresh-preserves-scratch-notes ()
  (should (eq (key-binding (kbd "C-c r ?")) 'lens-show-help))
  (lens-test-scratch
   (insert "我的笔记")
   (lens-show-help)
   (lens-show-help)
   (should (equal "我的笔记" (buffer-string)))
   (with-current-buffer "*Code Lens Help*"
     (should (derived-mode-p 'help-mode))
     (should buffer-read-only)
     (should (equal (buffer-string) (lens-help-text))))))

(ert-deftest lens-scratch-omits-magit-instructions ()
  (let ((text (lens-help-text)))
    (dolist (instruction '("Magit 内常用键" "Magit status" "magit-status"
                           "blame chunk" "stage（" "Git review"))
      (should-not (string-match-p (regexp-quote instruction) text)))
    (should (string-match-p "magit [0-9]" text))))

(ert-deftest lens-primary-package-summary-real-versions ()
  (should (fboundp 'lens-primary-package-summary))
  (let ((text (lens-primary-package-summary)))
    (dolist (name '(magit clojure-mode tuareg rainbow-delimiters
                         consult vertico orderless marginalia))
      (should (package-installed-p name))
      (let ((desc (cadr (assq name package-alist))))
        (should (string-match-p
                 (regexp-quote (format "%s %s" name
                                       (package-version-join (package-desc-version desc))))
                 text))))
    (dolist (name '(compat cond-let llama seq magit-section transient with-editor
                          project xref eglot imenu))
      (should-not (string-match-p (format "^  %s " name) text))))
  (let ((package-alist (assq-delete-all 'marginalia (copy-sequence package-alist))))
    (should-not (string-match-p "marginalia" (lens-primary-package-summary)))))

(ert-deftest lens-completion-orderless-real-candidates ()
  (dolist (name '(consult vertico orderless marginalia))
    (should (package-installed-p name)))
  (should vertico-mode)
  (should marginalia-mode)
  (should-not fido-mode)
  (should-not fido-vertical-mode)
  (should-not icomplete-mode)
  (dolist (input '("review answer" "answer review"))
    (should (equal "review-answer"
                   (car (completion-all-completions
                         input '("review-answer" "other-symbol") nil (length input))))))
  (let ((table (lambda (string predicate action)
                 (if (eq action 'metadata)
                     '(metadata (category . file))
                   (complete-with-action action '("src/review-answer.clj" "src/other.ml")
                                         string predicate)))))
    (should (equal "src/review-answer.clj"
                   (car (completion-all-completions "answer review" table nil 13))))))

(ert-deftest lens-marginalia-real-command-and-file-annotations ()
  (should (package-installed-p 'marginalia))
  (save-window-excursion
    (switch-to-buffer (current-buffer))
  (let* ((metadata '(metadata (category . command)))
         (affix (completion-metadata-get metadata 'affixation-function))
         (rows (and affix (funcall affix '("consult-line")))))
    (should (functionp affix))
    (should (string-match-p "matching line" (caddar rows))))
  (lens-test-project
   (let* ((metadata '(metadata (category . file)))
          (affix (completion-metadata-get metadata 'affixation-function))
          (rows (and affix (funcall affix (list clj)))))
     (should (functionp affix))
     (should (stringp (caddar rows)))
     (should (> (length (caddar rows)) 0))))))

(ert-deftest lens-consult-keys-and-xref ()
  (dolist (entry '(("C-s" . consult-line)
                   ("C-c r /" . lens-consult-search)
                   ("C-c r G" . lens-search)
                   ("C-c r L" . consult-line)
                   ("C-c r i" . consult-imenu)
                   ("C-c r I" . consult-imenu-multi)
                   ("C-x b" . consult-buffer)))
    (should (eq (key-binding (kbd (car entry))) (cdr entry))))
  (should (eq xref-show-xrefs-function 'consult-xref))
  (should (eq xref-show-definitions-function 'consult-xref)))

(ert-deftest lens-consult-real-ripgrep-builder ()
  (should (package-installed-p 'consult))
  (lens-test-project
   (with-temp-file ".gitignore" (insert "ignored.ml\n"))
   (with-temp-file "ignored.ml" (insert "let answer = 0\n"))
   (let* ((builder (consult--ripgrep-make-builder '(".")))
          (args (car (funcall builder "answer")))
          (text (with-temp-buffer
                  (should (zerop (apply #'call-process (car args) nil t nil (cdr args))))
                  (buffer-string))))
     (should (string-match-p "review.clj" text))
     (should (string-match-p "review.ml" text))
     (should-not (string-match-p "ignored.ml" text)))))

(defun lens-test-select-minibuffer (input match command)
  "Run COMMAND with real minibuffer INPUT and select a candidate matching MATCH."
  (let (timer selected minibuffer inserted
        (deadline (+ (float-time) 10)))
    (unwind-protect
        (minibuffer-with-setup-hook
            (:append
             (lambda ()
               (setq minibuffer (current-buffer))
               (setq timer
                     (run-at-time
                      0.05 0.05
                      (lambda ()
                        (when (and (buffer-live-p minibuffer) (active-minibuffer-window))
                          (with-current-buffer minibuffer
                            (unless inserted
                              (delete-minibuffer-contents)
                              (insert input)
                              (setq inserted t))
                            (if (> (float-time) deadline)
                                (abort-recursive-edit)
                              (vertico--update)
                              (when-let ((index (cl-position-if
                                                 (lambda (cand) (string-match-p match cand))
                                                 vertico--candidates)))
                                (setq selected (nth index vertico--candidates))
                                (vertico--goto index)
                                (vertico-exit))))))))))
          (call-interactively command))
      (when timer (cancel-timer timer)))
    (should selected)
    selected))

(ert-deftest lens-consult-interactive-line-and-imenu ()
  :tags '(interactive)
  (should (package-installed-p 'consult))
  (skip-unless (not noninteractive))
  (lens-test-project
   (switch-to-buffer (find-file-noselect clj))
   (goto-char (point-min))
   (lens-test-select-minibuffer "x 42" "x 42" #'consult-line)
   (should (= (line-number-at-pos) 3))
   (should buffer-read-only)
   (goto-char (point-max))
   (lens-test-select-minibuffer "answer" "answer" #'consult-imenu)
   (should (looking-at-p "(defn answer"))
   (should buffer-read-only)
   (switch-to-buffer (find-file-noselect ml))
   (goto-char (point-max))
   (lens-test-select-minibuffer "answer" "answer" #'consult-imenu)
   (should (looking-at-p "let answer"))
   (should buffer-read-only)))

(ert-deftest lens-consult-interactive-ripgrep-readonly ()
  :tags '(interactive)
  (should (package-installed-p 'consult))
  (skip-unless (not noninteractive))
  (lens-test-project
   (switch-to-buffer (find-file-noselect clj))
   (lens-test-select-minibuffer "#answer#review.ml" "review.ml" #'lens-consult-search)
   (should (equal (buffer-file-name) ml))
   (should buffer-read-only)
   (should-not (bound-and-true-p eglot--managed-mode))
   (should (string= "" (with-temp-buffer
                         (call-process "git" nil t nil "diff" "--") (buffer-string))))))

(ert-deftest lens-consult-line-common-mode-bindings ()
  (require 'magit)
  (require 'dired)
  (dolist (mode '(text-mode clojure-mode tuareg-mode emacs-lisp-mode
                           help-mode dired-mode magit-status-mode magit-diff-mode))
    (with-temp-buffer
      (funcall mode)
      (should (eq (key-binding (kbd "C-s")) 'consult-line))
      (should (eq (key-binding (kbd "C-c r L")) 'consult-line))))
  (let ((text (lens-help-text)))
    (should (string-match-p "C-s +.*当前文件行搜索.*\\[consult-line\\]" text))
    (should-not (string-match-p "C-s 仍为增量搜索" text))))

(ert-deftest lens-consult-interactive-c-s-select-and-cancel ()
  :tags '(interactive)
  (skip-unless (not noninteractive))
  (lens-test-project
   (dolist (file (list clj ml))
     (switch-to-buffer (find-file-noselect file))
     (goto-char (point-min))
     (let ((text (buffer-string)) (modified (buffer-modified-p)))
       (let (prompt)
         (minibuffer-with-setup-hook
             (:append (lambda () (setq prompt (minibuffer-prompt))))
           (execute-kbd-macro (vconcat (kbd "C-s") "x 42" (kbd "RET"))))
         (should (string-prefix-p "Go to line" prompt)))
       (should (save-excursion (beginning-of-line) (search-forward "42" (line-end-position) t)))
       (should buffer-read-only)
       (should (equal text (buffer-string)))
       (should (eq modified (buffer-modified-p)))))
   ;; Search typed, unsaved text and cancel through the real C-g input event.
   (switch-to-buffer (find-file-noselect clj))
   (read-only-mode -1)
   (goto-char (point-max))
   (insert "; user's unsaved search-note\n")
   (read-only-mode 1)
   (let ((text (buffer-string)) (origin (point)) prompt query minibuffer)
     (let ((capture (lambda (&rest _)
                      (when (equal (minibuffer-contents-no-properties) "unsaved search-note")
                        (setq query (minibuffer-contents-no-properties))))))
       (unwind-protect
           (minibuffer-with-setup-hook
               (:append
                (lambda ()
                  (setq prompt (minibuffer-prompt) minibuffer (current-buffer))
                  (add-hook 'after-change-functions capture nil t)))
             (execute-kbd-macro (vconcat (kbd "C-s") "unsaved search-note" (kbd "C-g"))))
         (when (buffer-live-p minibuffer)
           (with-current-buffer minibuffer (remove-hook 'after-change-functions capture t)))
         (setq quit-flag nil)))
     (should (string-prefix-p "Go to line" prompt))
     (should (equal query "unsaved search-note"))
     (should-not (active-minibuffer-window))
     (should (equal text (buffer-string)))
     (should (= origin (point)))
     (should (buffer-modified-p))
     (should buffer-read-only))))
