;;; ui-test.el --- Chrome and structure-only display checks -*- lexical-binding: t; -*-
(require 'ert)
(unless (ert-test-boundp 'lens-navigation-packages-and-header-compatibility)
  (load (expand-file-name "tests/navigation-display-test.el" lens-root) nil t))
(require 'lens-frame)
(ert-deftest lens-ui-chrome-defaults-and-terminal-safety ()
  (dolist (alist (list initial-frame-alist default-frame-alist))
    (should (equal (alist-get 'tool-bar-lines alist) 0))
    (should (eq (alist-get 'undecorated alist) t)))
  (when (boundp 'tool-bar-mode) (should-not tool-bar-mode))
  (should (memq #'lens-configure-frame after-make-frame-functions))
  (unless (display-graphic-p)
    (let ((before (frame-parameters)))
      (lens-configure-frame (selected-frame))
      (should (equal before (frame-parameters))))))
